### ISSUE TITLE
Inline SPIRV Assembly example does not compile

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3830] opened 2024-03-25 15:05 UTC
Hi,

I just tried to use some spirv inline assembly and started out with [the example given by the user guide](https://shader-slang.com/slang/user-guide/a1-04-interop.html#inline-spirv-assembly):
```c++
int test()
{
    int localVar = 5;
    return 1 + spirv_asm {
            %temp: $$int = OpIMul $localVar $(2);
            result: $$int = OpIAdd %temp %temp
        };
    // returns 21
}

[shader("compute")]
[numthreads(1, 1, 1)]
void computeMain() {
    test();
}
```
When compiling this using slang 2024.1.5 with this command line `slang/slangc.exe -entry computeMain -stage compute -target spirv-asm $file` this unfortunately results in this error:
```
shader.slang(20): internal error 99999: unimplemented feature in Slang compiler: unexpected IR opcode during code emit
    return 1 + spirv_asm {
                         ^
```
So either the example is wrong, or I am doing something wrong. Can you help me?

Thanks!

**Comment by csyonghe** [comment] 2024-03-25 15:57
The only thing suspicious here is the $(2) operand. If you define
int two=2;
And reference $two inside the block, does it still crash?

**Comment by pborsutzki** [comment] 2024-03-25 16:21
After trying around quite some while I found that it does compile when additionally setting `-emit-spirv-directly` on the command line. Not sure why this isn't the default when targeting spirv? Anyways, I couldn't guess that from the error message ...

So, if that's the way to go, you probably should document it somewhere next to the sample in the user guide and/or improve the error messag.

**Comment by csyonghe** [comment] 2024-03-25 17:04
@pborsutzki We have planned to make `-emit-spirv-directly` as default and deprecate the old glsl path.

**Comment by csyonghe** [comment] 2024-03-25 18:10
Since we know the cause here and we are going to fix the issue by switching to emit-spirv-directly as default anyways, I am going to close this issue.

**Closed by csyonghe** 2024-03-25 18:10 UTC
