### ISSUE TITLE
Immutable sampler for Ycbcr conversion, compiled with slang

### ISSUE THREAD

**Issue by BattleAxeVR** [shader-slang/slang#3443] opened 2024-01-11 08:26 UTC
Hi everyone, I could use some help fixing a difficult problem that seems to have no clear answer. 

To help in reproing the issue, I created a 100% repro test case in the Vulkan Video sample, using an HLSL shader compiled with both DXC and slang. Neither compiler seems able to output SPV binaries that are equivalent to the GLSL fragment shader, thus unable to do YCbCr conversion via immutable samplers. This is a serious problem for me as my path tracer needs to be able to sample video textures on the fly without converting them first to RGB, which I've done for a single texture but adds massive overhead.

This is the branch I made with 100% repro:

https://github.com/BattleAxeVR/vk_video_samples/tree/main/vk_video_decoder

If I compile this very basic HLSL pixel shader using slangc (all it does is sample a texture and draw on to a fullscreen quad), I can see my YUV 420 planar video textures but only the Y channel (so it looks red). 

The immutable texture sampler, whose job it is to automatically convert YUV planar textures to RGB, is clearly not bound or not working somehow, and I'm unable to figure out why. It's beyond my understanding and google is no help, really. Nobody seems to know

https://github.com/BattleAxeVR/vk_video_samples/blob/main/vk_video_decoder/video_pixel_shader.frag.hlsl

This is the command line I used:

**slangc video_pixel_shader.frag.hlsl -entry main -stage fragment -o video_pixel_shader.spv**

No other code is changed from the default GLSL pipeline, and dropping in the slang-compiled HLSL vertex shader into the demo works 100%. I tried everything but no idea what's going on. I originally tried using DXC but it exhibits the same issue: only showing red (first channel) instead of full colour.

This is what the bug looks like in my engine, but it's the same thing in the official Nvidia code sample. Video textures show up red instead of full colour.

Thanks for any help or insights you may have! 

![image](https://github.com/shader-slang/slang/assets/11604039/7a542230-b250-48ad-8362-c7b5919780b1)

**Comment by BattleAxeVR** [comment] 2024-01-11 08:26
This was originally created here:

https://github.com/nvpro-samples/vk_video_samples/issues/60

But it seems to be out of scope for that repository to fix.

**Comment by csyonghe** [comment] 2024-01-11 17:58
I noticed that your glsl code uses sampler2d, which is a combined texture sampler. The HLSL is using a separate sampler state so that could be the cause.

Looks like a driver issue though.

If you want the equivalent of combined texture sampler in slang, you can try using Sampler2D in Slang instead of Texture2D, which will map to sampler2d in glsl / spirv.

**Comment by natduca** [comment] 2024-01-11 19:03
If this is a driver issue, then maybe we should close this one but I'll post on the originating bug someone who can try to triage the issue and see if we can get it moving. Thanks, and sorry this issue on the other repo didn't get movement faster.

**Comment by natevm** [comment] 2024-01-11 19:33
> I noticed that your glsl code uses sampler2d, which is a combined texture sampler. The HLSL is using a separate sampler state so that could be the cause.
> 
> Looks like a driver issue though.
> 
> If you want the equivalent of combined texture sampler in slang, you can try using Sampler2D in Slang instead of Texture2D, which will map to sampler2d in glsl / spirv.

+1

Does switching over from Texture2D to Sampler2D fix the issue?

**Comment by BattleAxeVR** [comment] 2024-01-11 19:45
I will try this ASAP!

**Comment by BattleAxeVR** [comment] 2024-01-11 20:39
Sadly, it seems neither DXC nor slang support the DirectX 9 syntax of sampler2d and tex2, complaining about deprecated functionality or just missing identifiers:

![image](https://github.com/shader-slang/slang/assets/11604039/01790420-bc8d-46a6-a689-25ec5c7a69d8)

![image](https://github.com/shader-slang/slang/assets/11604039/dd562e74-46bf-4c2a-8b6a-ce1aa9ce12b3)

In DXC if I switch from sampler2d to sampler, it says tex2d is deprecated, regardless of whether I specify it's ps_4_0 or ps_6_6

![image](https://github.com/shader-slang/slang/assets/11604039/eafdaa64-e2f1-4001-98b9-21b0357712c2)

**Comment by BattleAxeVR** [comment] 2024-01-11 20:42
> If you want the equivalent of combined texture sampler in slang, you can try using Sampler2D in Slang instead of Texture2D, which will map to sampler2d in glsl / spirv.

Can you tell me what the equivalent of this HLSL shader is in slang? That would actually compile, at least

uniform sampler tex;

struct VSOutput
{
[[vk::location(0)]] float2 UV : TEXCOORD0;
};

float4 main(VSOutput input) : SV_TARGET
{
	float4 colour = tex2D(tex, input.UV);
	return colour;
}

**Comment by csyonghe** [comment] 2024-01-11 20:58
```
Sampler2D tex;
struct VSOutput
{
    float2 UV : TEXCOORD0;
};

float4 main(VSOutput input) : SV_TARGET
{
    float4 colour = tex.Sample(input.UV);
    return colour;
}
```

**Comment by csyonghe** [comment] 2024-01-11 21:00
`Sampler2D` has everything that `Texture2D` has, except that the `Sample` methods does not take an additional `SamplerState` parameter.

**Comment by csyonghe** [comment] 2024-01-11 21:00
<img width="831" alt="image" src="https://github.com/shader-slang/slang/assets/2652293/1ea9703c-8e1b-40e1-90fd-091247f8b49e">

**Comment by BattleAxeVR** [comment] 2024-01-11 21:14
That did it! Thanks so much! I had a feeling it was a syntax or binding issue like this.

DXC won't compile this code (I guess Sampler2D is a slang-specific identifier?). So it looks like slangd is the answer. 

I can close this now. What a relief.

![image](https://github.com/shader-slang/slang/assets/11604039/39bb7d9c-7e32-4f44-91e3-58f84cb4fab3)

**Closed** 2024-01-11 21:17 UTC

**Comment by csyonghe** [comment] 2024-01-11 21:26
Yes, Sampler2D is a Slang specific feature that gives our users direct access to combined texture samplers when targeting spirv or glsl.

According to the vulkan spec YCbCr textures only works with combined texture samplers, so `Sampler2D` is the right answer here.

**Comment by BattleAxeVR** [comment] 2024-01-12 00:21
For completeness, I tried tex.SampleLevel and tex.SampleGrad and the former works but SampleGrad crashes during pipeline creation. I enabled anisotropy and max aniso = 16 but didn't use the debug validation layers to see what the error was, but I'll open a new issue about it later. SampleLevel is an OK compromise for now, for my path tracer to manually pick the LOD even if aniso isn't done properly yet. Of course, I know that planar YUV 420 video textures don't actually have mips, but you should ideally be able to sample them anisotropically.

**Comment by BattleAxeVR** [comment] 2024-01-12 22:37
I got an alternative fix in DXC now, so this issue is truly closed with two viable alternatives. A+ everyone, so much appreciated! I have other slang use cases anyway, but for now I'll stick to DXC for this particular issue to avoid having to do a bunch of refactoring.

https://github.com/microsoft/DirectXShaderCompiler/issues/4179#issuecomment-1890069615
