### ISSUE TITLE
Update documentation for #include to indicate it is for legacy code and new code should use modules

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#4281] opened 2024-06-06 08:13 UTC
I have an Interfaces defined in `header A` and implement it in `Module B`. When I include `header A` and `Module B` in my main shader I can no longer find the Interface type with `layout->findTypeByName`, the implementation type I can find. When I exclude `Module B` from the main shader, I can find the interface but of course no longer the implementation.

```csharp
// header A
interface A {}

// Module B
#include "A"
struct B : A {};

// Main Shader that includes Module B
#include "A"
StructuredBuffer<A> buffer;
```

**Comment by bmillsNV** [comment] 2024-06-06 19:28
@fknfilewalker can you help to attach a better reproduction case and include any output from the slang compiler?

**Comment by fknfilewalker** [comment] 2024-06-06 20:18
I forgot to say that I compile the module with the interface implementation to a .slang-module and then later include that in my main shader.

Yes can do that, is it possible to set type conformance via command line so I can make this example quicker?

**Comment by csyonghe** [comment] 2024-06-13 19:16
We don't have a convenient way to set it via the command line, unfortunately.

**Comment by jkwak-work** [comment] 2024-06-27 21:07
I think @fknfilewalker found a solution for it.
Can we close this issue?

My understanding is that when you share an interface they must be `import`-ed.
If you use `#include`, the including file will be preprocessed and the definition of the interface will exist in the each and every translation units.
I don't think they will be combined and resulted in a single definition at the linking time only because their names are same.

If you still think this is a bug, please give us more concrete repro steps so that we can discuss at more detail.

**Comment by fknfilewalker** [comment] 2024-06-27 21:20
@jkwak-work you are absolutely right. I am fine with the module solution but of course it would be nice to also make this work with #include. There should be at least some kind of warning or info about that so people don't need to figure this out themselves.

**Closed** 2024-08-16 17:20 UTC
Labels: kind:documentation, goal:quality & productivity
