### ISSUE TITLE
AMD doesn't like passing structures with textures

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#144] opened 2017-07-24 12:47 UTC
I'm not sure what is the exactly the problem, but here's how to reproduce it.
* Run ModelViewer and load the alpha-test model under `Falcor/Media/alphatest`
* The model is a billboard of a leaf with a single texture - the alpha map. With every other API/Vendor, the alpha map is applied correctly. Not with Vulkan on AMD.

If I add the following to `ModelViewer.ps.glsl`
```C++
			if (!alphaTestPassed(gMaterial, shAttr))
				discard;
```
Then the test works. If I call `basicAlphaTest()` which essentially calls `alphaTestPassed()`, the alpha test stops working.

**Comment by tangent-vector** [comment] 2017-07-24 14:21
Is there and indication that Slang is generating invalid GLSL and/or glslang is generating invalid SPIR-V? If we identify some place where the generated SPIR-V is bad, I can try to fix it, but without that I don't have much hope of fixing the failure.

One other possibility to consider is that the shader code (or Slang's translation) relies on undefined behavior that doesn't work as we want on AMD.

Or it could be a plain old driver bug. Who knows?

I'll try to repro this. It would help a *lot* if you could post very clear "works" and "broken" shaders, with a description of what breaks.

**Comment by tfoleyNV** [comment] 2017-07-24 22:21
The source of the problem here (though maybe not the root cause) was that some shader parameters in Slang files were decorated `const` (which only affects mutability in HLSL), and Slang generated output GLSL that reproduced those `const` qualifiers. In GLSL, `const` is mostly used for true compile-time constants (think `constexpr`). My understanding of the language is that a `const` parameter should be treated more or less like HLSL `const`, but something about these `const` qualifiers was leading to bad results on the particular driver+hardware being tested.

For now the input code has been rewritten to not use `const` at all, but a better long-term solution would be for Slang to properly distinguish HLSL-`const` from GLSL-`const`.

**Comment by tfoleyNV** [comment] 2017-07-25 21:17
Closing this, since issue #145 captures the actual fix we need to make long-term.

**Closed by tfoleyNV** 2017-07-25 21:17 UTC
