### ISSUE TITLE
Compiler crash with array constructor and emit-spirv-directly

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#3468] opened 2024-01-22 05:17 UTC
Just hit this,

If I have the following code:

```
float3 p1, p2;
float3[2] test = float3[2](p1, p2);
```

Then the slangc compiler crashes with error code -1073741819.

But if I change to the following:
```
float3 p1, p2;
float3[2] test;
test[0] = p1;
test[1] = p2;
```

Then all is fine. 

Oddly, this seems to compile...
```
float3 test[2] = { float3(1.0), float3(1.0) };
```

**Comment by csyonghe** [comment] 2024-01-22 23:00
The constructor syntax is not supported in HLSL mode, but is implemented in GLSL compatibility mode. We should at least fix the compiler crash.

**Comment by csyonghe** [comment] 2024-02-07 01:43
I am not able to reproduce compiler crash.
The test I crafted:
```
RWStructuredBuffer<float3> outputBuffer;

[numthreads(2,1,1)]
void main(uint id : SV_DispatchThreadID)
{
    float3 p1, p2;
    float3[2] test = float3[2](p1, p2);
    outputBuffer[id] = test[id];
}
```
Tested with both direct spirv and glsl backend.
This crash could be due to something more subtle.

Can you provide a repro?

**Comment by csyonghe** [comment] 2024-02-07 20:05
I am closing this issue now due to inability to repro. Feel free to reopen anytime with a repro.

**Closed by csyonghe** 2024-02-07 20:05 UTC
Labels: priority:medium
