### ISSUE TITLE
Compilation of CSM shaders fail

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#102] opened 2017-07-15 22:34 UTC
Run the `Shadows` sample. It breaks inside Slang when trying to compile the `ShadowPass` shaders

**Comment by tangent-vector** [comment] 2017-07-16 18:36
Any particular error message(s)? Of is this a crash?

**Comment by nbenty** [comment] 2017-07-16 18:47
It crashes

**Comment by tfoleyNV** [comment] 2017-07-17 17:06
The initial crash here is because Slang hadn't implemented support for varying parameters with array types. I have some in-progress code to fix this issue, and I'll try to push a fix today.

The more serious issue (which is what stopped me from working on the above fix in favor of other issues) is that in this case we are trying to cross-compile a geometry shader, and as we discussed on slack, adding GS support to the cross compiler to handle just two framework shaders seems like a bit much. It certainly won't take priority over the other issues that have been filed.

**Comment by tfoleyNV** [comment] 2017-07-17 17:13
I'll go ahead and try to hand-write an equivalent GS in raw GLSL and Falcor can use that for now. Eventually when I add GS cross-compilation support I can use that hand-written output to help me know what to reproduce.

**Comment by tfoleyNV** [comment] 2017-07-17 17:30
A hand-written GS seems like it may work, and then the next issue is that `gl_Layer` as a fragment input requires GLSL version 4.30 or higher. There are a few fixes possible for that:

1. Make the Falcor fragment shader not declare that input (if it doesn't use it)
2. Make Falcor use the new capabilities in Slang to specify a desired target GLSL version
3. Make the Slang emit logic smart enough to bump up the required GLSL version when cross-compiling, if it sees a construct that requires a higher version

I'm going to try (3)

**Comment by tfoleyNV** [comment] 2017-07-17 21:11
The compilation failures should be addressed by #111. I'm closing this for now, although the downstream failures in Falcor may be due to things Slang is doing in incorrect or unexpected ways.

**Closed by tfoleyNV** 2017-07-17 21:11 UTC
