### ISSUE TITLE
Issue with InterlockedCompareExchange causing errors in FXC

### ISSUE THREAD

**Issue by vasumahesh1** [shader-slang/slang#723] opened 2018-11-19 05:32 UTC
Hi,

I have an issue with a [compute shader](https://github.com/vasumahesh1/azura/blob/dev/Source/Samples/0_TestZone/Shaders/Cloth.cs.slang) which isn't compiling to DXBC (incorrect HLSL). (Ignore the weird spacing etc. This was on a test sandbox)

I think it is got to do with the `InterlockedCompareExchange`. Because right before that, the code was compiling correctly.

I don't have the error log, but slang started renaming variables like threadIdx with an extra count.

Like `threadIdx` was transpiled to `threadIdx_0` but the error fxc showed was that a variable `threadIdx_1` is not defined. Probably affected Vulkan too.

Tried it on 0.11.6 and 0.11.10.

EDIT:

[File with commit hash](https://github.com/vasumahesh1/azura/blob/b98e216e07853014edebfcb48f804e1693125d3a/Source/Samples/0_TestZone/Shaders/Cloth.cs.slang) attached since I am working actively in a group so this file tends to change a lot.

**Comment by tfoleyNV** [comment] 2018-11-19 17:16
Thanks for filing this. Slang uses a compiler technique called static single assignment (SSA) form, which ends up splitting single variables into multiple, which usually explains why you'd see both `threadIdx_0` and `threadIdx_1` in the same function.

If Slang is failing to declare any of those variables, though, that is a serious bug. Looking at the code you linked, there appears to be some complicated control flow going on, so that I suspect a bug in Slang's handling of control-flow related analysis passes.

I will look into this, but I will caution you that we are quite busy on other priorities, and there is a holiday this week for many in the US, so turnaround may not be fast. Hopefully you can find suitable workarounds for now. I might try moving as much of the logic of your shader out to separate subroutines as possible, so that you don't have a single function with such complex control flow. I don't know if that would be enough to work around the bug (since I'm not sure what the problem is), but it could be a worth a shot.

**Comment by vasumahesh1** [comment] 2018-11-19 19:58
Alright, this is for a project that has a few milestones due on the Monday after the holidays.

I could do the compute logic in multiple passes, I guess I will give that a try. Thanks!

**Comment by tfoleyNV** [comment] 2018-12-03 21:40
I am going to start looking at this bug now. Thank you for being patient.

**Comment by tfoleyNV** [comment] 2018-12-03 23:57
I believe I have a fix for this implemented in PR #739. Hopefully that change can be merged and put into a new release this week.

The underlying bug was a subtle one, so thank you for helping us find and fix it!

**Comment by vasumahesh1** [comment] 2018-12-04 20:01
No problem, I eventually had to breakdown my compute shader into multiple passes.

**Closed** 2018-12-04 21:57 UTC
Labels: bug, ir
