### ISSUE TITLE
Import and namespaces

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2208] opened 2022-04-25 16:43 UTC
Take the following example

In "a.slang"

```HLSL
public int foo(int a) {  return a * a + 1; }
```

And 

```HLSL
import a;

RWStructuredBuffer<int> outputBuffer;

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    int index = (int)dispatchThreadID.x;
    outputBuffer[index] = foo(index);
}
```

Works as expected. Let's add a namespace around that import

```HLSL
namespace Zing {
import a;
} 
```

This produces an error...

```
tests/language-feature/modules/import-check/import-check.slang(20): error 30015: undefined identifier 'foo'.
    outputBuffer[index] = foo(index);
                          ^~~
```

This seems a little surprising when documentation says...

> An import declaration searches for a module matching the name given in the declaration, and brings the declarations in that module into scope in the current source unit.

Maybe this means in the current scope of the *import*. Such that the declarations inside the module are now available in the namespace. This seems to raise a whole different bunch of questions...., but leaving that aside if I try...

```HLSL
    outputBuffer[index] = Zing::foo(index);
```
 
This also doesn't work...

```
tests/language-feature/modules/import-check/import-check.slang(20): error 30027: 'foo' is not a member of 'namespace Zing'.
    outputBuffer[index] = Zing::foo(index);
```

If I change the source to 

```
namespace Zing {
import a;
int check(int a) { return foo(a); }
} //

//TEST_INPUT:ubuffer(data=[0 0 0 0 ], stride=4):out,name outputBuffer
RWStructuredBuffer<int> outputBuffer;

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    int index = (int)dispatchThreadID.x;    
    outputBuffer[index] = Zing::check(index);
}
```

This *does* compile but the foo function *isn't* in the output HLSL (just a function forward declaration). Leading to DXC to output 

```
dxc: : error : error: External function used in non-library profile: \01?foo_0@@YAHH@Z
```

**Comment by tangent-vector** [comment] 2022-04-25 17:22
At the time `import` got added, we didn't have `namespace` support, so that explains at least some of the problems here.

It is worth noting that there are really two different kinds of constructs that often use similar terminology and even overlapping syntax in various languages:

* A "top-level" construct that can bring names into scope from a module
* A "local" construct that can take an already-visible entity (like a `namespace`) and make its contents visible inside another entity/scope

What makes the two cases important to understand separately is that the "top-level" construct will often have rules that allow it to look up names that would not otherwise be visible. For example, consider if we have a Slang module:

    // Foo.slang
    float getValue() { return 0.0f; }

We know we can access that stuff with `import`:

    // A.slang
    import Foo;
    float a() { return getValue(); }

However, the `import Foo` line doesn't mean that `Foo` was in scope when compiling. If we try:

    // B.slang
    float b() { return Foo.getValue(); }

we will get an "undefined identifier" error on `Foo`. Making that not be the case would involve a significant change to how name lookup works throughout the compiler, and I don't think we could justify it.

Thus there is an important note to be made about `import Foo`, in that it does *not* require the identifer `Foo` to be visible in the current scope, and instead actually uses it more like a string identifier for something to search for.

In contrast, something like `using namespace Foo` in C++ requires that `Foo` would already resolve as an identifier in the current scope. A user could change all their use sites to have `Foo::` as a prefix, and things would Just Work (modulo aliased/shadowed names).

Similarly, in C#, any time you have `using Foo` the identifier `Foo` was already usable/visible. This works even for the "top-level" case in C# because of the way the compiler requires the list of referenced modules to be specified separately from the source code (typically via command-line arguments).

For Slang, we thus have a design decision to make. It seems like we can either:

1. Keep the current semantics of `import`, where `import Foo` can trigger a search for `Foo.slang` (or eventually a pre-compiled module file for `Foo`), and thus need to devise a distinct construct with different semantics for anything like a `using namespace Bar`.

2. Try to have a unified construct for both top-level and local `using`, and thus need to find a way to phase out the current `import` semantics where modules can be looked up and loaded automagically.

I know that the original question here was more narrowly scoped: trying to use the current `import` construct under a `namespace`. I just wanted to up-level this a bit to make sure our approach to the issue is holistic.

**Comment by jsmall-nvidia** [comment] 2022-04-28 15:50
In the short term, making import only work at module scope is probably a good option.

**Comment by natduca** [comment] 2023-12-01 19:02
Yong is suggesting we document this as part of language spec. We'll file a bug for documenting this behavior and close this one.

**Closed by natduca** 2023-12-01 19:02 UTC
