### ISSUE TITLE
Invlid spirv generated from buffer pointer

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#3621] opened 2024-02-23 22:48 UTC
After having [this](https://github.com/shader-slang/slang/issues/3601) fixed, 
the generated spirv i get is invalid according to the vulkan validation layers (my app also crashes when i still run):
```
VUID-VkShaderModuleCreateInfo-pCode-08737(ERROR / SPEC): msgNum: -1520283006 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282 | vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: OpVariable 159: expected AliasedPointer or RestrictPointer for PhysicalStorageBuffer pointer.
  %159 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_PP Function
. The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08737)
    Objects: 0
```
The repro is the same as in the issue i linked.

**Comment by csyonghe** [comment] 2024-02-23 23:46
It appears that this is a spirv-opt bug. Run `slangc` with `-O0` to disable spirvopt and you will get a valid SPIRV. I suggest you open an issue for spirvopt, and provide the slang output using `-O0`.

**Comment by csyonghe** [comment] 2024-02-23 23:47
It seems that the latest spirvopt has fixed this issue, so it might just be that we need to update spirv tools that is built into slang.

**Comment by csyonghe** [comment] 2024-02-24 00:36
I can confirm that this is a spirv-opt bug.

Steps to reproduce:
```
> slangc test.slang -target spirv -emit-spriv-directly -O0 -o test.spv
> spirv-val test.spv             // should pass validation here
> spirv-opt test.spv --inline-entry-points-exhaustive -o out.spv
> spirv-val out.spv            // broken!
```

**Comment by csyonghe** [comment] 2024-02-24 03:06
Closing this issue now since there isn't much we can do in the Slang codebase.

**Closed by csyonghe** 2024-02-24 03:06 UTC
Labels: goal:quality & productivity

**Comment by csyonghe** [comment] 2024-03-11 03:54
Update: I filed a bug for spirv-opt here: https://github.com/KhronosGroup/SPIRV-Tools/issues/5607
