### ISSUE TITLE
Workgroup memory unexpected behavior

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#4983] opened 2024-09-02 23:25 UTC
The following compute shader performs incorrect shared memory operations:
```hlsl
[[vk::binding(1, 0)]] RWTexture2D<float4> textures[];
struct Push
{
    uint tex_index;
};
[[vk::push_constant]] Push p; 
groupshared float3 shared_stuff[2];
[numthreads(1, 1, 1)]
[shader("compute")]
void main()
{
    shared_stuff[0] = float3(1.0f, 2.0f, 3.0f);
    shared_stuff[1] = float3(4.0f, 5.0f, 6.0f);
    // GroupMemoryBarrierWithGroupSync(); // <- not necessary, dispatch of one thread. Also changes nothing when added.
    printf("stuff1  %f %f %f\n", shared_stuff[0].x, shared_stuff[0].y, shared_stuff[0].z); // Should print 1.000000 2.000000 3.000000
    printf("stuff2  %f %f %f\n", shared_stuff[1].x, shared_stuff[1].y, shared_stuff[1].z); // Should print 4.000000 5.000000 6.000000
    // Prints:
    // stuff1  1.000000 2.000000 4.000000 <- this should be 3.0!
    // stuff2  4.000000 5.000000 6.000000
    textures[p.tex_index][uint2(0,0)] = float4(1,1,1,1); // Somehow a write to an image is necessary?! Removing this fixes it!
}
```

As you can see in the comments, the texture write is somehow required to reproduce this. 
It also seems necessary to have an array or multiple shared memory variables.
The shared values must also be float3 or some other vec3 type (maybe some scalar layout issue?).

Config:
```
Slang Version: 2024.9
pc platform: x86-64msvc windows11
slang::TargetDesc::format: SlangCompileTarget::SLANG_SPIRV
slang::TargetDesc::profile: glsl_450+spirv_1_4
slang::TargetDesc::flags: SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY
slang::TargetDesc::forceGLSLScalarBufferLayout = true
slang::SessionDesc::defaultMatrixLayoutMode: SLANG_MATRIX_LAYOUT_COLUMN_MAJOR
```

**Comment by Ipotrick** [comment] 2024-09-02 23:26
@MatejSakmary

**Comment by csyonghe** [comment] 2024-09-04 02:17
This is very likely a downstream compiler bug or some weird memory model behavior.

Have you tried this on a GPU from a different vendor?

**Comment by Ipotrick** [comment] 2024-09-04 17:49
I just tested on my amd igpu (rdna3) and it indeed works.
The bug only appears to come up on ada nvidia gpus.

**Comment by Ipotrick** [comment] 2024-09-04 17:52
Are you certain the spirv does not contain ub that leaves the drivers to have different interpretations of what should happen?

**Comment by GabeRundlett** [comment] 2024-09-04 17:56
I tested on the latest driver for my RTX 3070. Same broken behavior on NVIDIA
![image](https://github.com/user-attachments/assets/cf9fdf79-baf0-421b-8d06-5862b53297df)

**Comment by Ipotrick** [comment] 2024-09-04 18:09
It might be caused by the validation layers somehow. When i pump the shared memory  values through the image, the values turn out correct.

**Comment by csyonghe** [comment] 2024-09-04 18:20
What version of validation layer and the drivers are you using? Testing this out on my machine with a slightly modified shader, things seem to be correct.

Shader used for testing:
```
//TEST(compute, vulkan):COMPARE_COMPUTE_EX:-vk -compute -shaderobj -output-using-type

//TEST_INPUT: set textures = [RWTexture2D(format=R16G16_FLOAT, size=4, content = one, mipMaps = 1)]

RWTexture2D<float4> textures[3];

//DTEST_INPUT:ubuffer(data=[0], stride=4):out,name outputBuffer
//RWStructuredBuffer<float> outputBuffer;

//TEST_INPUT: set tex_index = 0;
uniform uint tex_index; 
groupshared float3 shared_stuff[2];
[numthreads(1, 1, 1)]
[shader("compute")]
void computeMain()
{
    shared_stuff[0] = float3(1.0f, 2.0f, 3.0f);
    shared_stuff[1] = float3(4.0f, 5.0f, 6.0f);
    // GroupMemoryBarrierWithGroupSync(); // <- not necessary, dispatch of one thread. Also changes nothing when added.
    printf("stuff1  %f %f %f\n", shared_stuff[0].x, shared_stuff[0].y, shared_stuff[0].z); // Should print 1.000000 2.000000 3.000000
    printf("stuff2  %f %f %f\n", shared_stuff[1].x, shared_stuff[1].y, shared_stuff[1].z); // Should print 4.000000 5.000000 6.000000
    // Prints:
    // stuff1  1.000000 2.000000 4.000000 <- this should be 3.0!
    // stuff2  4.000000 5.000000 6.000000
    textures[0][uint2(0, 0)] = float4(1, 1, 1, 1); // Somehow a write to an image is necessary?! Removing this fixes it!
}
```
Output:
```
stuff1  1.000000 2.000000 3.000000
stuff2  4.000000 5.000000 6.000000
```
I am using nv driver 551.23 with vulkan sdk 1.3.283.0

**Comment by Ipotrick** [comment] 2024-09-04 18:30
My validation layers are quite old, Im using them from the vulkan sdk 1.3.268.
I just tried to replicate the error with glslang and it didnt replicate.
I will now update my sdk and try again with slang.

**Comment by Ipotrick** [comment] 2024-09-04 18:37
With the latest sdk 1.3.290 it still replicates with slang for me.

**Comment by csyonghe** [comment] 2024-09-04 18:38
The only difference here is I am not using unsized arrays for the texture, and not using push constants. Can you try making those modifications to see if the problem still persist?

**Comment by Ipotrick** [comment] 2024-09-04 18:46
When i remove array tex and push constant it no longer reproduces.
With a fixes size texture array it Does reproduce.
Not using a dynamic index into the texture array but a constant makes it no longer reproduce.

**Comment by Ipotrick** [comment] 2024-09-04 18:49
Updating drivers also didnt help btw.

**Comment by csyonghe** [comment] 2024-09-04 18:53
In that case, can you share with us the app you used to reproduce this issue? We can't reproduce it within slang's testing infra since we haven't implemented push constant support yet.

**Comment by Ipotrick** [comment] 2024-09-04 18:59
Ah i just found out that there are other fields required in the push constant to reproduce this.
The push constant needs to have a buffer pointer in it for this to reproduce for some reason.

I can prodide the app.
I will clean a little push and then you can clone and try it.

**Comment by Ipotrick** [comment] 2024-09-04 19:00
```
[[vk::binding(1, 0)]] RWTexture2D<float4> textures[];
struct Push
{
    uint tex_index;
    daxa_u32* ptr;
};
[[vk::push_constant]] Push p; 
groupshared float3 shared_stuff[2];
[numthreads(1, 1, 1)]
[shader("compute")]
void main()
{
    shared_stuff[0] = float3(1.0f, 2.0f, 3.0f);
    shared_stuff[1] = float3(4.0f, 5.0f, 6.0f);
    // GroupMemoryBarrierWithGroupSync(); // <- not necessary, dispatch of one thread. Also changes nothing when added.
    printf("stuff1  %f %f %f\n", shared_stuff[0].x, shared_stuff[0].y, shared_stuff[0].z); // Should print 1.000000 2.000000 3.000000
    printf("stuff2  %f %f %f\n", shared_stuff[1].x, shared_stuff[1].y, shared_stuff[1].z); // Should print 4.000000 5.000000 6.000000
    // Prints:
    // stuff1  1.000000 2.000000 4.000000 <- this should be 3.0!
    // stuff2  4.000000 5.000000 6.000000
    textures[p.tex_index][uint2(0,0)] = float4(1,1,1,1); // Somehow a write to an image is necessary?! Removing this fixes it!
}
```

**Comment by csyonghe** [comment] 2024-09-04 19:01
I see, looks like a bug linked with variable pointers.

**Comment by Ipotrick** [comment] 2024-09-04 19:06
```
struct Test
{
    uint tex_index;
    uint * ptr;
};
[[vk::binding(0, 0)]] StructuredBuffer<Test> buffer;
groupshared float3 shared_stuff[2];
[numthreads(1, 1, 1)]
[shader("compute")]
void main()
{
    uint i = buffer[0].tex_index;
    shared_stuff[0] = float3(1.0f + i, 2.0f, 3.0f);
    shared_stuff[1] = float3(4.0f, 5.0f, 6.0f);
    // Prints:
    // stuff1  1.000000 2.000000 4.000000 <- this should be 3.0!
    // stuff2  4.000000 5.000000 6.000000
    printf("stuff1  %f %f %f\n", shared_stuff[0].x, shared_stuff[0].y, shared_stuff[0].z); // Should print 1.000000 2.000000 3.000000
    printf("stuff2  %f %f %f\n", shared_stuff[1].x, shared_stuff[1].y, shared_stuff[1].z); // Should print 4.000000 5.000000 6.000000
}
```
This also reproduces it and does not use a push constant.

**Comment by csyonghe** [comment] 2024-09-04 19:29
We have confirmed that this is a bug in the driver. I have forwarded this issue to the driver team for further investigation. We will keep this thread updated as we make progress on the fix.

**Comment by Ipotrick** [comment] 2024-09-05 00:07
thank you very much!

**Comment by csyonghe** [comment] 2024-09-17 00:36
As an update, this is a known issue in the driver where an array of 12-byte sized vector that isn't 16-byte aligned is miscompiled. The workaround suggested by the driver team is to always use 16-byte aligned arrays, which means float4 arrays when VariablePointer capability is used in the spirv (i.e. when pointers are being used).

**Comment by csyonghe** [comment] 2024-09-27 23:43
Closing this issue now since this is not a Slang bug. Will update here once we are able to confirm the fix in the nvidia driver.

**Closed by csyonghe** 2024-09-27 23:43 UTC
Labels: kind:bug, goal:client support
