### ISSUE TITLE
slang-test: Some tests show up as passing even though they print out error messages

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5291] opened 2024-10-14 11:58 UTC
- `tests/language-feature/shader-params/entry-point-uniform-params-implicit.slang`
- `tests/metal/groupshared-threadlocal-same-parameter.slang`
- `tests/bugs/gh-2959.slang`
- `tests/bugs/gh-471.slang`
- `tests/bugs/static-var.slang`
- `tests/bugs/texture2d-gather.hlsl `
- `tests/language-feature/anonymous-struct.slang`
- `tests/language-feature/constants/static-const-in-generic-interface.slang`
- `tests/language-feature/enums/nested-enum.slang`
- `tests/language-feature/enums/strongly-typed-id.slang`
- `tests/language-feature/generics/variadic-void.slang`
- `tests/language-feature/generics/variadic-0.slang`
- `tests/language-feature/generics/tuple.slang`
- `tests/language-feature/generics/irwarray.slang`

Example:

    ...
    WGPU error: Binding doesn't exist in [BindGroupLayout (unlabeled)].
     - While validating that the entry-point's declaration for @group(0) @binding(1) matches [BindGroupLayout (unlabeled)]
     - While validating the entry-point's compatibility for group 0 with [BindGroupLayout (unlabeled)]
     - While validating compute stage ([ShaderModule (unlabeled)], entryPoint: computeMain).
     - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor]).
    
    WGPU error: Number of entries (1) did not match the expected number of entries (0) for [BindGroupLayout (unlabeled)].
    Expected layout: []
     - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
     - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
    
    WGPU error: [Invalid ComputePipeline (unlabeled)] is invalid.
     - While encoding [ComputePassEncoder (unlabeled)].SetPipeline([Invalid ComputePipeline (unlabeled)]).
     - While finishing [CommandEncoder (unlabeled)].
    
    WGPU error: [Invalid CommandBuffer] is invalid.
     - While calling [Queue].Submit([[Invalid CommandBuffer]])
    
    Warning: Old MapAsync APIs are deprecated. If using C please pass a CallbackInfo struct that has two userdatas. Otherwise, if using C++, please use templated helpers.
    passed test: 'tests/language-feature/shader-params/entry-point-uniform-params-implicit.slang.3 syn (wgpu)' 
    Retrying 0 failed tests...
    
    ===
    100% of tests passed (1/1), 3 tests ignored
    ===

**Comment by aleino-nv** [comment] 2024-10-14 12:16
@csyonghe This is pretty worrying. I hope it's not some issue with slang-test itself!

**Comment by aleino-nv** [comment] 2024-10-14 12:21
- 'inff' float literal: https://github.com/shader-slang/slang/issues/5280
   - tests/bugs/inf-float-literal.slang
- Binding missing from bind group layout: https://github.com/shader-slang/slang/issues/5222
   - tests/autodiff/global-param-hoisting.slang
   - tests/bindings/nested-parameter-block-2.slang
   - tests/compute/cbuffer-legalize.slang
   - tests/compute/column-major.slang
   - tests/compute/constant-buffer-memory-packing.slang
   - tests/compute/func-cbuffer-param.slang
   - tests/compute/interface-shader-param-in-struct.slang
   - tests/compute/interface-shader-param.slang
   - tests/compute/kernel-context-threading.slang
   - tests/compute/loop-unroll.slang
   - tests/compute/matrix-layout.hlsl
   - tests/compute/matrix-layout.hlsl
   - tests/compute/non-square-column-major.slang
   - tests/compute/non-square-column-major.slang
   - tests/compute/non-square-row-major.slang
   - tests/compute/parameter-block.slang
   - tests/compute/parameter-block.slang
   - tests/compute/row-major.slang
   - tests/compute/row-major.slang
   - tests/hlsl/packoffset.slang
   - tests/language-feature/generics/parameter-block-unify.slang
   - tests/language-feature/inheritance/struct-inheritance.slang
   - tests/language-feature/shader-params/entry-point-uniform-params.slang
   - tests/language-feature/tuple/tuple-parameter.slang
- Capability for numerical types: https://github.com/shader-slang/slang/issues/4947
   - tests/bugs/buffer-swizzle-store.slang
   - tests/bugs/op-assignment-unify-mat.slang
   - tests/compute/transcendental-double.slang
   - tests/hlsl-intrinsic/matrix-int.slang
- Finite array of runtime-sized arrays: https://github.com/shader-slang/slang/issues/5221#issuecomment-2407202272 (TODO: follow up on thread and decide whether to file separate issue for this)
   - tests/compute/buffer-type-splitting.slang
- Intel vkCreateDevice crash: https://github.com/shader-slang/slang/issues/5275
   - tests/bugs/atomic-coerce.slang
   - tests/bugs/frexp-double.slang
   - tests/bugs/frexp.slang
   - tests/bugs/generic-type-duplication.slang
   - tests/bugs/gh-3980.slang
   - tests/bugs/shadowed-lookup.slang
   - tests/hlsl-intrinsic/classify-double.slang
   - tests/hlsl-intrinsic/classify-float.slang
   - tests/hlsl-intrinsic/matrix-float.slang
   - tests/hlsl-intrinsic/scalar-double-simple.slang
   - tests/language-feature/higher-order-functions/simple.slang
   - tests/language-feature/swizzles/matrix-swizzle-write-array.slang
   - tests/language-feature/swizzles/matrix-swizzle-write-single.slang
   - tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang
   - tests/language-feature/swizzles/matrix-swizzle-write.slang
   - tests/pipeline/compute/compute-system-values.slang
- Mismatching values in autodiff tests: https://github.com/shader-slang/slang/issues/5290
   - tests/autodiff/matrix-arithmetic-fwd.slang
   - tests/autodiff/reverse-loop-checkpoint-test.slang
- Nested structures in entry point IO: https://github.com/shader-slang/slang/issues/5226
   - tests/compute/compile-time-loop.slang
   - tests/compute/constexpr.slang
- No texture_1d_array type: https://github.com/shader-slang/slang/issues/5223
   - tests/compute/texture-get-dimensions.slang
   - tests/compute/texture-sampling.slang
   - tests/compute/texture-simple.slang
- Marked by slang-test as passing, but clearly have errors output: https://github.com/shader-slang/slang/issues/5291
   - tests/bugs/gh-2959.slang
   - tests/bugs/gh-471.slang
   - tests/bugs/static-var.slang
   - tests/language-feature/anonymous-struct.slang
   - tests/language-feature/constants/static-const-in-generic-interface.slang
   - tests/language-feature/enums/nested-enum.slang
   - tests/language-feature/enums/strongly-typed-id.slang
   - tests/language-feature/generics/irwarray.slang
   - tests/language-feature/generics/tuple.slang
   - tests/language-feature/generics/variadic-0.slang
   - tests/language-feature/generics/variadic-void.slang
   - tests/language-feature/shader-params/entry-point-uniform-params-implicit.slang
   - tests/metal/groupshared-threadlocal-same-parameter.slang
- Passing runtime-sized arrays: https://github.com/shader-slang/slang/issues/5228
   - tests/autodiff/diff-ptr-type-call.slang
   - tests/autodiff/diff-ptr-type-loop.slang
   - tests/autodiff/diff-ptr-type-smoke.slang
   - tests/bindings/nested-parameter-block-3.slang
   - tests/bugs/gh-518.slang
   - tests/bugs/gh-566.slang
   - tests/bugs/obfuscate-specialization-naming.slang
   - tests/bugs/specialize-function-array-args.slang
   - tests/compute/func-param-legalize.slang
   - tests/compute/func-resource-param.slang
   - tests/compute/kernel-context-threading.slang
   - tests/language-feature/shader-params/interface-shader-param-ordinary.slang
   - tests/language-feature/types/opaque/inout-param-opaque-type-in-struct.slang
   - tests/language-feature/types/opaque/inout-param-opaque-type.slang
   - tests/language-feature/types/opaque/out-param-opaque-type-in-struct.slang
   - tests/language-feature/types/opaque/out-param-opaque-type.slang
   - tests/language-feature/types/opaque/return-opaque-type-in-struct.slang
   - tests/language-feature/types/opaque/return-opaque-type.slang
- Semantics:  https://github.com/shader-slang/slang/issues/4940
   - tests/compute/texture-simpler.slang
- Signed-unsigned comparison: https://github.com/shader-slang/slang/issues/5262
   - tests/autodiff/bug-1.slang
- Unexpected IR opcode: https://github.com/shader-slang/slang/issues/5263
   - tests/autodiff/custom-intrinsic.slang
- Unfilterable-float sampler used to filter: https://github.com/shader-slang/slang/issues/5227
   - tests/compute/discard-stmt.slang
- Uniform elements with stride less than 16: https://github.com/shader-slang/slang/issues/4985
   - tests/compute/non-square-row-major.slang
- WGSL: Emitting 4079520790 as 'i32': https://github.com/shader-slang/slang/issues/5286
   - tests/ir/string-literal-hash.slang
   - tests/ir/string-literal.slang
- WGSL: Initialize signed int with unsigned int: https://github.com/shader-slang/slang/issues/5283
   - tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang
- WGSL: Runtime-sized array as return value: https://github.com/shader-slang/slang/issues/5288
   - tests/optimization/func-resource-result/func-resource-result-simple.slang
- WGSL: Ternary operator emitted: https://github.com/shader-slang/slang/issues/5289
   - tests/autodiff-dstdlib/dstdlib-abs.slang
- WGSL: missing return: https://github.com/shader-slang/slang/issues/5282
   - tests/hlsl-intrinsic/scalar-float.slang
   - tests/hlsl-intrinsic/vector-float.slang
- WGSL: pointer formed to texture: https://github.com/shader-slang/slang/issues/5278
   - tests/bugs/mutating/resource-specialization-inout.slang
- WGSL: texture_2d<f32> used as an element type of an array: https://github.com/shader-slang/slang/issues/5279
   - tests/bugs/dxbc-double-problem.slang
   - tests/optimization/func-resource-result/func-resource-result-complex.slang
- emitStructFieldAttributes crash: https://github.com/shader-slang/slang/issues/5264
   - tests/autodiff/existential-1.slang
   - tests/autodiff/existential-2.slang
   - tests/autodiff/material/diff-bwd-falcor-material-system.slang
   - tests/autodiff/material2/diff-bwd-falcor-material-system.slang
- nullptr deref in ShaderObjectImpl::writeSamplerDescriptor: https://github.com/shader-slang/slang/issues/5277
   - tests/bugs/user-attribute-lookup.slang
- slang-test assert on usePassthru: https://github.com/shader-slang/slang/issues/5276
   - tests/bugs/texture2d-gather.hlsl
- slang-test: cannot access as blob: https://github.com/shader-slang/slang/issues/5284
   - tests/hlsl-intrinsic/sampler-feedback/compute-sampler-feedback.slang
- switch without default: https://github.com/shader-slang/slang/issues/5281
   - tests/bugs/nested-switch.slang
- texturesamplelevel offset must be const: https://github.com/shader-slang/slang/issues/5287
   - tests/language-feature/constants/constexpr-loop.slang

All 103 failures mentioned above are included here, but I also found some extra issues.
Each failure goes into one out of 28 issues.

**Comment by jkwak-work** [comment] 2024-10-17 15:40
I added `tests/bugs/texture2d-gather.hlsl` to the list.

**Comment by cheneym2** [comment] 2024-10-30 19:41
The first several cases did not repro anything other than a warning for me, but I did repro with texture2d-gather.hlsl

```
$ build/Debug/bin/slang-test.exe tests/bugs/texture2d-gather.hlsl
Supported backends: fxc dxc glslang spirv-dis clang visualstudio genericcpp spirv-opt tint
Check vk,vulkan: Supported
Check dx12,d3d12: Supported
Check dx11,d3d11: Supported
Check cuda: Not Supported
Check wgpu,webgpu: Supported
passed test: 'tests/bugs/texture2d-gather.hlsl (dx11)'
ignored test: 'tests/bugs/texture2d-gather.hlsl.1 (mtl)'
WGPU error: Error while parsing WGSL: :32:6 error: nested structures cannot be used for entry point IO
     assembledVertex_0 : AssembledVertex_0,
     ^^^^^^^^^^^^^^^^^

:36:1 note: while analyzing entry point 'vertexMain'
fn vertexMain( input_0 : VertexStageInput_0) -> VertexStageOutput_0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
{
^
    var output_0 : VertexStageOutput_0;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    var _S2 : vec4<f32> = (((vec4<f32>(input_0.assembledVertex_0.position_1, 1.0f)) * (unpackStorage_0(Uniforms_0.modelViewProjection_0))));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    output_0.position_0 = _S2;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    var _S3 : vec4<f32> = vec4<f32>(input_0.assembledVertex_0.color_1, 1.0f);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    output_0.color_0 = _S3;
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return output_0;
^^^^^^^^^^^^^^^^^^^^
}
^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).

WGPU error: Error while parsing WGSL: :7:6 error: missing entry point IO attribute
     color_0 : vec4<f32>,
     ^^^^^^^

:12:1 note: while analyzing entry point 'fragmentMain'
fn fragmentMain( input_0 : VertexStageOutput_0) -> vec4<f32>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
{
^
    var _S1 : vec4<f32> = (textureGather((i32(0)), (g_texture_0), (g_sampler_0), (input_0.color_0.xy)));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _S1;
^^^^^^^^^^^^^^^
}
^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).

WGPU error: Buffer usages (BufferUsage::(MapWrite|CopySrc|CopyDst)) is invalid. If a buffer usage contains BufferUsage::MapWrite the only other allowed usage is BufferUsage::CopySrc.
 - While calling [Device].CreateBuffer([BufferDescriptor "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"]).

WGPU error: [Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"] is invalid.
 - While calling [Queue].WriteBuffer([Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"], (0 bytes), data, (96 bytes))

Warning: Old OnSubmittedWorkDone APIs are deprecated. If using C please pass a CallbackInfo struct that has two userdatas. Otherwise, if using C++, please use templated helpers.
WGPU error: [Invalid ShaderModule (unlabeled)] is invalid.
 - While validating vertex stage ([Invalid ShaderModule (unlabeled)], entryPoint: vertexMain).
 - While validating vertex state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor]).

Warning: Old MapAsync APIs are deprecated. If using C please pass a CallbackInfo struct that has two userdatas. Otherwise, if using C++, please use templated helpers.
WGPU error: Number of entries (3) did not match the expected number of entries (2) for [BindGroupLayout (unlabeled)].
Expected layout: [{ binding: 0, visibility: ShaderStage::(Vertex|Fragment|Compute), texture: {sampleType: TextureSampleType::UnfilterableFloat, viewDimension: 2, multisampled: 0} }, { binding: 1, visibility: ShaderStage::(Vertex
|Fragment|Compute), sampler: {type: SamplerBindingType::Filtering} }]
 - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

WGPU error: [Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"] is invalid.
 - While encoding [RenderPassEncoder (unlabeled)].SetVertexBuffer(0, [Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"], 0, 96).
 - While finishing [CommandEncoder (unlabeled)].

WGPU error: [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

WGPU error: [Texture "Unnamed texture (type=Texture2D, size=1024x768x1, arrayLength=1, mipLevelCount=1, sampleCount=1, sampleQuality=0, format=R8G8B8A8_UNORM, memoryType=DeviceLocal, usage=RenderTarget, defaultState=RenderTarget
)"] usage (TextureUsage::RenderAttachment) doesn't include TextureUsage::CopySrc.
 - While validating source [Texture "Unnamed texture (type=Texture2D, size=1024x768x1, arrayLength=1, mipLevelCount=1, sampleCount=1, sampleQuality=0, format=R8G8B8A8_UNORM, memoryType=DeviceLocal, usage=RenderTarget, defaultSta
te=RenderTarget)"] usage.
 - While encoding [CommandEncoder (unlabeled)].CopyTextureToBuffer([Texture "Unnamed texture (type=Texture2D, size=1024x768x1, arrayLength=1, mipLevelCount=1, sampleCount=1, sampleQuality=0, format=R8G8B8A8_UNORM, memoryType=Dev
iceLocal, usage=RenderTarget, defaultState=RenderTarget)"], [Buffer (unlabeled)], [Extent3D width:1024, height:768, depthOrArrayLayers:1]).
 - While finishing [CommandEncoder (unlabeled)].

WGPU error: [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

WGPU error: Error while parsing WGSL: :32:6 error: nested structures cannot be used for entry point IO
     assembledVertex_0 : AssembledVertex_0,
     ^^^^^^^^^^^^^^^^^

:36:1 note: while analyzing entry point 'vertexMain'
fn vertexMain( input_0 : VertexStageInput_0) -> VertexStageOutput_0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
{
^
    var output_0 : VertexStageOutput_0;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    var _S2 : vec4<f32> = (((vec4<f32>(input_0.assembledVertex_0.position_1, 1.0f)) * (unpackStorage_0(Uniforms_0.modelViewProjection_0))));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    output_0.position_0 = _S2;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    var _S3 : vec4<f32> = vec4<f32>(input_0.assembledVertex_0.color_1, 1.0f);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    output_0.color_0 = _S3;
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return output_0;
^^^^^^^^^^^^^^^^^^^^
}
^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).

WGPU error: Error while parsing WGSL: :7:6 error: missing entry point IO attribute
     color_0 : vec4<f32>,
     ^^^^^^^

:12:1 note: while analyzing entry point 'fragmentMain'
fn fragmentMain( input_0 : VertexStageOutput_0) -> vec4<f32>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
{
^
    var _S1 : vec4<f32> = (textureGather((i32(0)), (g_texture_0), (g_sampler_0), (input_0.color_0.xy)));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _S1;
^^^^^^^^^^^^^^^
}
^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).

WGPU error: Buffer usages (BufferUsage::(MapWrite|CopySrc|CopyDst)) is invalid. If a buffer usage contains BufferUsage::MapWrite the only other allowed usage is BufferUsage::CopySrc.
 - While calling [Device].CreateBuffer([BufferDescriptor "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"]).

WGPU error: [Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"] is invalid.
 - While calling [Queue].WriteBuffer([Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"], (0 bytes), data, (96 bytes))

Warning: Old OnSubmittedWorkDone APIs are deprecated. If using C please pass a CallbackInfo struct that has two userdatas. Otherwise, if using C++, please use templated helpers.
WGPU error: [Invalid ShaderModule (unlabeled)] is invalid.
 - While validating vertex stage ([Invalid ShaderModule (unlabeled)], entryPoint: vertexMain).
 - While validating vertex state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor]).

Warning: Old MapAsync APIs are deprecated. If using C please pass a CallbackInfo struct that has two userdatas. Otherwise, if using C++, please use templated helpers.
WGPU error: Number of entries (3) did not match the expected number of entries (2) for [BindGroupLayout (unlabeled)].
Expected layout: [{ binding: 0, visibility: ShaderStage::(Vertex|Fragment|Compute), texture: {sampleType: TextureSampleType::UnfilterableFloat, viewDimension: 2, multisampled: 0} }, { binding: 1, visibility: ShaderStage::(Vertex
|Fragment|Compute), sampler: {type: SamplerBindingType::Filtering} }]
 - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

WGPU error: [Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"] is invalid.
 - While encoding [RenderPassEncoder (unlabeled)].SetVertexBuffer(0, [Invalid Buffer "Unnamed buffer (size=96, elementSize=0, format=Unknown, memoryType=Upload, usage=VertexBuffer, defaultState=VertexBuffer)"], 0, 96).
 - While finishing [CommandEncoder (unlabeled)].

WGPU error: [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

WGPU error: [Texture "Unnamed texture (type=Texture2D, size=1024x768x1, arrayLength=1, mipLevelCount=1, sampleCount=1, sampleQuality=0, format=R8G8B8A8_UNORM, memoryType=DeviceLocal, usage=RenderTarget, defaultState=RenderTarget
)"] usage (TextureUsage::RenderAttachment) doesn't include TextureUsage::CopySrc.
 - While validating source [Texture "Unnamed texture (type=Texture2D, size=1024x768x1, arrayLength=1, mipLevelCount=1, sampleCount=1, sampleQuality=0, format=R8G8B8A8_UNORM, memoryType=DeviceLocal, usage=RenderTarget, defaultSta
te=RenderTarget)"] usage.
 - While encoding [CommandEncoder (unlabeled)].CopyTextureToBuffer([Texture "Unnamed texture (type=Texture2D, size=1024x768x1, arrayLength=1, mipLevelCount=1, sampleCount=1, sampleQuality=0, format=R8G8B8A8_UNORM, memoryType=Dev
iceLocal, usage=RenderTarget, defaultState=RenderTarget)"], [Buffer (unlabeled)], [Extent3D width:1024, height:768, depthOrArrayLayers:1]).
 - While finishing [CommandEncoder (unlabeled)].

WGPU error: [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

passed test: 'tests/bugs/texture2d-gather.hlsl.2 syn (wgpu)'
passed test: 'tests/bugs/texture2d-gather.hlsl.3 syn (dx12)'

===
100% of tests passed (3/3), 1 tests ignored
===

```

**Comment by cheneym2** [comment] 2024-11-01 18:46
The following wgsl source is passed into wgpuDeviceCreateShaderModule(), and despite producing errors on console, it returns a non-null pointer which is treated as success by slang-rhi:

```
module.module = m_device->m_ctx.api.wgpuDeviceCreateShaderModule(m_device->m_ctx.device, &desc);
if (!module.module)
{
    return SLANG_FAIL;
}
```

```
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_Uniforms_std140_0
{
    @align(16) modelViewProjection_0 : _MatrixStorage_float4x4std140_0,
};

@binding(2) @group(0) var<uniform> Uniforms_0 : SLANG_ParameterGroup_Uniforms_std140_0;
fn unpackStorage_0( _S1 : _MatrixStorage_float4x4std140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(3)][i32(3)]);
}

struct VertexStageOutput_0
{
     color_0 : vec4<f32>,
     position_0 : vec4<f32>,
};

struct AssembledVertex_0
{
     position_1 : vec3<f32>,
     color_1 : vec3<f32>,
     uv_0 : vec2<f32>,
};

struct VertexStageInput_0
{
     assembledVertex_0 : AssembledVertex_0,
};

@vertex
fn vertexMain( input_0 : VertexStageInput_0) -> VertexStageOutput_0
{
    var output_0 : VertexStageOutput_0;
    var _S2 : vec4<f32> = (((vec4<f32>(input_0.assembledVertex_0.position_1, 1.0f)) * (unpackStorage_0(Uniforms_0.modelViewProjection_0))));
    output_0.position_0 = _S2;
    var _S3 : vec4<f32> = vec4<f32>(input_0.assembledVertex_0.color_1, 1.0f);
    output_0.color_0 = _S3;
    return output_0;
}

```


This error output shows up:

```
WGPU error: Error while parsing WGSL: :32:6 error: nested structures cannot be used for entry point IO
     assembledVertex_0 : AssembledVertex_0,
     ^^^^^^^^^^^^^^^^^

:36:1 note: while analyzing entry point 'vertexMain'
fn vertexMain( input_0 : VertexStageInput_0) -> VertexStageOutput_0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
{
^
    var output_0 : VertexStageOutput_0;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    var _S2 : vec4<f32> = (((vec4<f32>(input_0.assembledVertex_0.position_1, 1.0f)) * (unpackStorage_0(Uniforms_0.modelViewProjection_0))));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    output_0.position_0 = _S2;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    var _S3 : vec4<f32> = vec4<f32>(input_0.assembledVertex_0.color_1, 1.0f);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    output_0.color_0 = _S3;
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return output_0;
^^^^^^^^^^^^^^^^^^^^
}
^


 - While validating [ShaderModuleDescriptor]
```

**Comment by cheneym2** [comment] 2024-11-01 20:28
The error itself can be seen in isolation using this website:
https://shader-playground.timjones.io/ba069f6097736b8793be6c115107fd4f

But the issue is the lack of an error code coming out of wgpuDeviceCreateShaderModule, which seems to be returning success according to the non-null return.  I guess that's a Dawn issue, or a user error, not sure yet which.

**Comment by csyonghe** [comment] 2024-11-01 21:25
Let's not worry about fixing this issue for now, and instead we should focus on addressing the invalid wgsl output by Slang.
I believe @jkwak-work is already working on addressing the issue.

**Comment by csyonghe** [comment] 2024-11-01 21:26
Thanks for getting to the bottom of this, @cheneym2. Given that we know this is not a bug in our stack, I think we should close this issue.

**Comment by jkwak-work** [comment] 2024-11-02 15:22
Yes I am working on the error with tests/bugs/texture2d-gather.hlsl

Is it only test printing error message?
And the rest of them are printing just warnings?

**Comment by aleino-nv** [comment] 2024-11-04 06:03
WebGPU uses an error callback to report errors. 
https://github.com/shader-slang/slang-rhi/blob/eaed14f275306c5c8a6240b4d40be742894d135e/src/wgpu/wgpu-device.cpp#L14

At the moment we just print them out. 
Perhaps we should look at the error type in some cases, and respond to the error that way?

**Comment by cheneym2** [comment] 2024-11-04 15:13
I think we need to propagate the error seen in the callback, as Anders mentioned and not close the issue until then.

**Comment by cheneym2** [comment] 2024-11-04 16:35
https://github.com/shader-slang/slang-rhi/pull/95 would make the failed compilation at least return SLANG_FAIL, which is faithfully recorded as a failed error code by the test harness, however, being an HLSL comparison test, the fact that the HLSL and Slang paths both return the same compilation error, texture2d-gather.hlsl still passes.

**Comment by cheneym2** [comment] 2024-11-04 17:00
The inner test in spawnAndWaitSharedLibrary sees an error code, storing it in ExecuteResult outRes.errorCode
https://github.com/shader-slang/slang/blob/master/tools/slang-test/slang-test-main.cpp#L847 and returns SLANG_OK as the return from spawnAndWaitSharedLibrary().

doRenderComparisonTestRun merely builds the error code into an output string, and returns TestResult::Pass.
In this, both the "expected" and "actual" runs show the same "TestResult::Pass" return value and same output string that shows wgsl compilation failed.

**Comment by csyonghe** [comment] 2024-11-04 17:25
The test should definitely propagate any error code and return Fail when shader compilation failed.

**Comment by cheneym2** [comment] 2024-11-04 19:05
Testing https://github.com/shader-slang/slang/pull/5485/files#diff-45451d657441da687eb40563c21b977d64ba42d643fd5783a1bc937b3eac62b3 as a possible fix, though I assume it will also require disabling newly failing tests once I see which they are.

**Closed** 2024-11-07 00:46 UTC
Labels: kind:bug, goal:forward looking, siggraphasia-2024
