### ISSUE TITLE
Fix sccache stability issue.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#5163] opened 2024-09-26 17:29 UTC
This is failing frequent enough that we need a way to mitigate the issue.

**Comment by jkwak-work** [comment] 2024-09-26 21:32
![image](https://github.com/user-attachments/assets/8e5ed12b-2950-42bf-a224-8e0326b93de2)
Copilot says we can use `SCCACHE_IGNORE_SERVER_IO_ERROR=1`.

And the [doc](https://github.com/mozilla/sccache) says,
```
By default, sccache will fail your build if it fails to successfully communicate with its associated server. To have sccache instead gracefully failover to the local compiler without stopping, set the environment variable SCCACHE_IGNORE_SERVER_IO_ERROR=1.
```

**Comment by jkwak-work** [comment] 2024-09-26 22:26
I tested the environment variable little bit.
It appears to work well.
Whenever `cmake` is used, we should add `export SCCACHE_IGNORE_SERVER_IO_ERROR=1` at the beginning of the workflow step.

**Comment by aleino-nv** [comment] 2024-09-27 12:41
Here is what it looks like:


    ...
    [253/1109] Building CXX object external\spirv-tools\source\CMakeFiles\SPIRV-Tools-static.dir\Release\software_version.cpp.obj
    FAILED: external/spirv-tools/source/CMakeFiles/SPIRV-Tools-static.dir/Release/software_version.cpp.obj 
    sccache C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\cl.exe  /nologo /TP -DSPIRV_COLOR_TERMINAL -DSPIRV_WINDOWS -DCMAKE_INTDIR=\"Release\" -IC:\actions-runner-2\_work\slang\slang\external\spirv-tools -IC:\actions-runner-2\_work\slang\slang\external\spirv-tools\include -IC:\actions-runner-2\_work\slang\slang\build\external\spirv-tools -IC:\actions-runner-2\_work\slang\slang\external\spirv-headers\include /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG /MT -std:c++17 -MT   /MP4 /W0 -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS /wd4800 /wd4819 /EHs -WX /showIncludes /Foexternal\spirv-tools\source\CMakeFiles\SPIRV-Tools-static.dir\Release\software_version.cpp.obj /Fdexternal\spirv-tools\source\CMakeFiles\SPIRV-Tools-static.dir\Release\SPIRV-Tools-static.pdb /FS -c C:\actions-runner-2\_work\slang\slang\external\spirv-tools\source\software_version.cpp
    sccache: error: failed to execute compile
    sccache: caused by: Failed to send data to or receive data from server
    sccache: caused by: Failed to read response header
    sccache: caused by: An existing connection was forcibly closed by the remote host. (os error 10054)
    [254/1109] Building CXX object external\spirv-tools\source\CMakeFiles\SPIRV-Tools-static.dir\Release\print.cpp.obj
    FAILED: external/spirv-tools/source/CMakeFiles/SPIRV-Tools-static.dir/Release/print.cpp.obj 
    sccache C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\cl.exe  /nologo /TP -DSPIRV_COLOR_TERMINAL -DSPIRV_WINDOWS -DCMAKE_INTDIR=\"Release\" -IC:\actions-runner-2\_work\slang\slang\external\spirv-tools -IC:\actions-runner-2\_work\slang\slang\external\spirv-tools\include -IC:\actions-runner-2\_work\slang\slang\build\external\spirv-tools -IC:\actions-runner-2\_work\slang\slang\external\spirv-headers\include /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG /MT -std:c++17 -MT   /MP4 /W0 -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS /wd4800 /wd4819 /EHs -WX /showIncludes /Foexternal\spirv-tools\source\CMakeFiles\SPIRV-Tools-static.dir\Release\print.cpp.obj /Fdexternal\spirv-tools\source\CMakeFiles\SPIRV-Tools-static.dir\Release\SPIRV-Tools-static.pdb /FS -c C:\actions-runner-2\_work\slang\slang\external\spirv-tools\source\print.cpp
    sccache: error: failed to execute compile
    sccache: caused by: Failed to send data to or receive data from server
    sccache: caused by: Failed to read response header
    sccache: caused by: An existing connection was forcibly closed by the remote host. (os error 10054)
    ...

**Comment by csyonghe** [comment] 2024-09-27 18:52
This is not fixed. It happened again here: https://github.com/shader-slang/slang/actions/runs/11075544340/job/30776734274?pr=5176

Reopening the issue for further investigation.

**Comment by jkwak-work** [comment] 2024-09-27 23:58
Unfortunately, the error, "sccache: caused by: Failed to send data to or receive data from server", is unrelated to the environment variable, "SCCACHE_IGNORE_SERVER_IO_ERROR".
And there doesn't seem to be any way to failback to the local compilation for these cases.

**Comment by csyonghe** [comment] 2024-09-28 00:19
Should we be using this action instead: https://github.com/Mozilla-Actions/sccache-action
We are currently using https://github.com/hendrikmuhs/ccache-action, which states that support for windows is unstable.

**Comment by expipiplus1** [comment] 2024-09-28 02:06
ccache support for windows was deemed unstable, hence sccache (which obviously isn't great either).

I evaluated both and chose the non-mozilla action because of better support for utilizing the github cache, but if we set up a s3 bucket then switching to the mozilla one is a good idea. I suggest we just disable it completely for the time being as it's clearly using up a lot of time.

**Comment by csyonghe** [comment] 2024-09-28 02:10
yes, let's disable it for now.

**Comment by expipiplus1** [comment] 2024-09-30 13:40
Looks like the mozilla one has changed a little since last year, lets give it a try: https://github.com/shader-slang/slang/pull/5189

**Comment by expipiplus1** [comment] 2024-10-09 08:23
see also https://github.com/shader-slang/slang/issues/4835

**Comment by jkwak-work** [comment] 2024-10-15 02:43
Closing the issue because this hadn't been an issue for the past five days.

**Closed by jkwak-work** 2024-10-15 02:43 UTC
Labels: goal:quality & productivity
