### ISSUE TITLE
Regression, "left of '=' is not an l-value", error 30011

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5348] opened 2024-10-18 17:04 UTC
A regression is reported and the error message is as following,
```
$ slangc.exe ../polynomial_soa.slang
../polynomial_soa.slang(92): error 30011: left of '=' is not an l-value.
    call_data._result_primal[{call_id[0]}] = val;
```

The regression happened from [PR 5177](https://github.com/shader-slang/slang/pull/5177).

TODO: I will add a repro shade code here once ready.

**Comment by csyonghe** [comment] 2024-10-18 22:52
Closing this as not a bug.

**Closed by csyonghe** 2024-10-18 22:52 UTC
Labels: goal:client support, kind:regression
