### ISSUE TITLE
Cross linux binaries for slang-llvm

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2592] opened 2023-01-13 17:22 UTC
In the recent past github Actions supported Ubuntu 18.04 as a target. Support has subsequently [been depreciated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/). The [current github hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) make Ubuntu 20.4 the oldest.

In slangs [LLVMProject](https://github.com/shader-slang/llvm-project) we use github actions to build static LLVM binaries that can then be used to build [slang-llvm](https://github.com/shader-slang/slang-llvm). Since the last time LLVM was updated was a while ago, it's release binaries *were* built under 18.04.

In order to create binaries that work across a wide variety of linux targets a typical strategy has been to build on an older version of linux as older binaries generally work on newer versions of linux. It appears to be fairly common to build linux binaries under CentOS 7 in part for this particular reason.

It turns out there are users of slang-llvm that require it be built with an older version of ubuntu than 20.04. 

This presents a problem as it's not clear how to build 18.04 binaries on self hosted github Actions. In lots of other ways building with github actions is great.

An attempt was made to work around this problem using [holy build box](https://phusion.github.io/holy-build-box/). This didn't work out for two reasons 

1) LLVMProject doesn't *quite* compile under HBB, it gets 90%+ through and then fails in the linker in a crash for unknown reasons
2) Using HBB works on github Actions, but requires a docker image/docker. The extra resources required mean LLVM compilation can't complete

On the second point perhaps it's of note that github actions is not able to build debug LLVM for similar reasons. 

This leaves LLVM/slang-llvm in a problematic place. We can't build new binaries such that they are accessed from github via deps. We can't upgrade LLVM - we can no longer build on github for 18.04.  

We also may have issues around fixing/improving slang-llvm as it will build it's binaries with different version of linux (as it cannot be 18.04), and a different version of C/C++ compiler. That may mean linking between slang-llvm and LLVM isn't possible.

Hosting (say) CentOS 7.0 or Ubuntu 18.04 option ourselves is a possibility, but adds significant ongoing effort to maintain/secure and so forth.

Additionally there *may* be an argument for building ubuntu18.04 binaries and updating LLVMProject and slang-llvm now, as whilst the target is depreciated and not always available doing so might provide more flexibility around finding future solutions.

**Comment by expipiplus1** [comment] 2023-01-16 14:33
Is it a kernel version issue or a system library one? A statically linked version might do the trick (perhaps excluding libstdc++ as that's sometimes hard to statically link to)

**Comment by natduca** [comment] 2023-12-01 00:48
I think this is dupe of #2997. Closing.

**Closed by natduca** 2023-12-01 00:48 UTC
Labels: kind:enhancement, priority:high
