### ISSUE TITLE
Using Slang v0.9.6 with the FeatureDemo results in a black image

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#343] opened 2018-01-02 03:05 UTC
Trying to run the FeatureDemo from the `ShadingSystem` branch, v0.9.6 results in black image.
v0.9.5 works as expected.

I haven't debugged it, not sure what the problem is.

**Comment by tfoleyNV** [comment] 2018-01-02 18:45
Looking at this now.

**Comment by tfoleyNV** [comment] 2018-01-02 19:05
I was able to pull top-of-tree `ShadingSystem` and to-of-tree Slang (should match `v0.9.7`) and didn't see an immediately obvious problem for the Classroom scene (there is one bit of the wall that seems to be lit when it shouldn't be, but everything else seemed fine).

I'll try `v0.9.6` now, so see if I can repro the issue (maybe something regressed, but then got fixed?).

**Comment by tfoleyNV** [comment] 2018-01-02 19:10
Confirmed that `v0.9.6` has a problem. I'm going to try and diff the output shader code to see if I can identify what changed.

**Comment by tfoleyNV** [comment] 2018-01-02 19:22
The culprit seems to be #315, which I knew was a little wonky and had pushed a fix for later. My guess is that the problem stems from this line in the generated shader code:

```hlsl
 float oneOverNine = 1 / 9;
```

That should obviously be `1.0 / 9.0`, but the way I was printing floating-point literals in that version of things was broken (despite being a change intended to *fix* floating-pointer literal printing).

I'm going to close this since `v0.9.7` should clear up the issue, and we already have open issues for our bad behavior around printing floats.

**Closed by tfoleyNV** 2018-01-02 19:22 UTC
Labels: bug, falcor
