### ISSUE TITLE
Do uniforms have incorrect "set" index in Spirv?

### ISSUE THREAD

**Issue by vasumahesh1** [shader-slang/slang#646] opened 2018-09-20 03:43 UTC
Hi,

I was trying slang for a while and noticed for SPIRV (and GLSL) the ParameterBlock is converted to a uniform with `set=1` decorator. Shouldn't that be `set=0`?

Input: shader.slang:
```hlsl
struct UBOData {
    float4x4 model;
    float4x4 view;
    float4x4 proj;
};

ParameterBlock<UBOData> ubo;
```

GLSL output:
```glsl
layout(binding = 0, set = 1)
layout(std140) uniform _S1
{
    UBOData_0 ubo_0;
};
```

Shouldn't set be 0? Same with SPIRV's disassembly: `OpDecorate %_ DescriptorSet 1`

I am trying to run some vulkan code, and my pipeline layout has only 1 descriptor set which is set 0. Is there any specific reason to go with set 1?

Ran on Slang binary: v0.10.32

**Comment by tfoleyNV** [comment] 2018-09-20 03:56
If your shader has no other parameters in the global scope then that would seem to be a bug, yes.

If a shader combines explicit parameter blocks with other global shader parameters (a common case) then the ordinary global parameters will get set zero, while the explicit blocks will start at set one.

I will try to debug this tomorrow and see if I can confirm that this is a bug.

**Comment by vasumahesh1** [comment] 2018-09-20 04:04
Thanks for a speedy reply!

Here is my full code (just a basic test shader):
```hlsl
struct UBOData {
    float4x4 model;
    float4x4 view;
    float4x4 proj;
};

ParameterBlock<UBOData> ubo;

struct VertexShaderInput
{
    float4 inPosition : POSITION;
    float4 inColor : COLOR;
};

struct PixelShaderInput
{
    float4 pos : SV_Position;
    float4 color : COLOR;
};

PixelShaderInput main(VertexShaderInput input)
{
  PixelShaderInput output;

  output.pos = mul(ubo.proj, mul(ubo.view, mul(ubo.model, input.inPosition)));
  output.color = input.inColor;

  return output;
}
```

Executed command:
```
slangc test.slang -profile vs_5_0 -entry main -o test.glsl
```

Output:
```
#version 450
layout(row_major) uniform;
layout(row_major) buffer;

#line 1 0
struct UBOData_0
{
    mat4x4 model_0;
    mat4x4 view_0;
    mat4x4 proj_0;
};


#line 7
layout(binding = 0, set = 1)
layout(std140) uniform _S1
{
    UBOData_0 ubo_0;
};

.........
```

**Comment by tfoleyNV** [comment] 2018-09-20 15:33
Thanks for the code. I've been able to reproduce this and can confirm what is going on.

The problem here is that Slang is allocating a sampler in the "default" set (set zero) to use when cross-compiling certain HLSL operations that don't have a direct equivalent in unextended GLSL for Vulkan. That means that *no matter what* there ends up being a sampler allocated into set zero (even if it doesn't make it into the output code), and so the compiler moves the parameter block to set one because it thinks set zero is already occupied.

That sampler is a workaround for something that got mis-specified in the original GLSL-for-Vulkan extension, and has since been solved with the `GL_EXT_samplerless_texture_functions` extension. I will need to convert Slang to use that extension by default to solve this issue.

**Comment by vasumahesh1** [comment] 2018-09-20 17:21
Also, I noticed that the amount of SPIRV instructions are far more if I do it manually via GLSL and glslang. I'm not sure how much of a performance difference it would make if the shader is pretty big.

Any thoughts regarding that?

**Comment by tfoleyNV** [comment] 2018-09-20 20:30
The changes in #648 are necessary for a fix to this issue, but don't appear to be sufficient. I'm testing on top of that PR and I still see the paramter block getting set one. I need to confirm what that is happening and submit a separate fix. This will possibly get fixed tomorrow, but it may have to wait until next week if the answer isn't simple.

**Comment by tfoleyNV** [comment] 2018-09-20 20:37
Okay, I diagnosed it an patched up something I missed in #648, so when that pull request lands this issue should also be fixed. With that PR applied I get output like the following:

```glsl
#version 450
layout(row_major) uniform;
layout(row_major) buffer;

struct UBOData_0
{
    mat4x4 model_0;
    mat4x4 view_0;
    mat4x4 proj_0;
};

layout(binding = 0)
layout(std140) uniform _S1
{
    UBOData_0 ubo_0;
};

//...
```

The `layout(binding = 0)` there should implicitly be for `set=0`.

**Comment by vasumahesh1** [comment] 2018-09-20 23:56
Awesome, Thanks for everything!

**Comment by tfoleyNV** [comment] 2018-09-22 15:16
You are correct that each `ParameterBlock` is assigned a new `set`. This is by design, because different parameter blocks are meant to represent different update frequencies, and in Vulkan you should use different descriptor tables when binding things at different rates.

By default, all the “uniform” data in a `ParameterBlock<X>` (that is, all the fields of `X` that aren’t resources) will be put in a UBO that gets `binding` zero within the set, and all of the resources will get `binding`s 1,2,3, etc. in the same set.

If you want multiple UBO declarations to come from one parameter block, then you should use the `ConstantBuffer<T>` type inside your data:

```hlsl
struct A { float4 x; };
struct B { float4 y; ConstantBuffer<A> a; };

ParameterBlock<B> b;
```

The above code should produce two UBO declarations both in `set` zero. That parameter block would need to be bound with a descriptor set that has two uniform buffer descriptors in it.

Does that help clarify things? It seems like some better documentation of how `ParameterBlock` works would be helpful.

**Comment by vasumahesh1** [comment] 2018-09-22 16:54
Gotcha, thanks that helps a lot. Should this issue be closed now?

**Comment by tfoleyNV** [comment] 2018-09-22 17:15
The fix isn’t incorporated in a release yet, so I will close out the issue when that happens. Thanks again for pointing this out!

**Comment by tfoleyNV** [comment] 2018-09-24 17:29
Slang `v0.10.34` should now include the fix for this issue.

**Closed by tfoleyNV** 2018-09-24 17:29 UTC
Labels: bug, cross compilation, reflection
