### ISSUE TITLE
Slang outputs struct definition in the wrong order [URGENT]

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#333] opened 2017-12-27 21:34 UTC
I tried adding back `MaterialData` into `LightData`. This resulted in a compilation error - `CameraData is undefined`.
Instead of `MaterialData` I tried to add a single texture into `LightData`, but that resulted in the same error.
To reproduce:
- Add a `Texture2D` field to `LightData`
- Run the feature-demo and load a scene.
- The compilation error occurs when trying to compile `MaterialBlock.slang`.

The following Slang IR file shows that there's indeed an error. `CameraData` is first used in line 95 but only defined in line 114. I'm not sure why adding a texture causes this error.

[slang-dump.txt](https://github.com/shader-slang/slang/files/1589911/slang-dump.txt)

This is a high-priority issue as it blocks area-lights and light-probe support in Falcor.

**Comment by csyonghe** [comment] 2018-01-01 23:47
Seems this is a bug related to `SLANG_COMPILE_FLAG_NO_CHECKING`.
You may temporarily work around the issue by removing that flag in Program.cpp

**Comment by tfoleyNV** [comment] 2018-01-02 00:23
@nbenty are you on the latest Slang? I thought I fixed an issue related to the order that `struct` definitions get emitted before the holidays.

@csyonghe leaving off the flag isn’t a viable option for Falcor. They need to be able to compile those declarations together with HLSL or GLSL that might use constructs we don’t support (and thus can’t check).

I can make this my first priority tomorrow.

**Comment by csyonghe** [comment] 2018-01-02 00:26
I am also having this problem trying to run latest slang in the slang-integration branch of Falcor. I turned off the flag and the issue is gone.

________________________________

**Comment by tfoleyNV** [comment] 2018-01-02 01:46
Yes, we can potentially just disable the flag in our branch for now, but I’ll repeat that it isn’t a viable fix for mainline Falcor unless their requirements change.

**Comment by nbenty** [comment] 2018-01-02 02:46
@tfoleyNV Falcor is on v0.9.5, but the same issue happens with v0.9.6.

**Comment by tfoleyNV** [comment] 2018-01-02 16:59
I think I have a fix for this issue. I'll test it and try to put out a new release shortly.

**Closed** 2018-01-02 17:29 UTC
