### ISSUE TITLE
Question: How does Slang handle forward declaration of functions

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4429] opened 2024-06-19 03:12 UTC
Curious how slang handles forward declaration of functions. I'm porting the shader below from HLSL to Slang and getting an ambiguous function call error. It seems like the forward declarations are being seen as actual functions. Was wondering if Slang will support HLSL style forward declarations where forward declarations are global and ostensibly unscoped?

**Shader**
```
struct foo
{
  float memberFunction() {
    float MulBy3(float f);
    return MulBy3(.25);
  }
};

float4 main() : SV_Target
{
  foo f;
  float a = f.memberFunction();

  float MulBy2(float f);

  return float4(MulBy2(.25), 1, 0, 1);
}

float MulBy2(float f) {
  return f*2;
}

float MulBy3(float f) {
  return f*3;
}

```

**Comment by jkwak-work** [comment] 2024-06-26 05:06
I think this question was answered on another issue.
Can @chaoticbob confirm that is the case?

As far as I know, Slang doesn't support forward declaration of functions.

**Comment by jkwak-work** [comment] 2024-06-28 05:27
I am closing this since the goal of the issue is to answer the question.

There is another issue tracking a documentation work regarding the forward declaration, #4446, so this issue is at least duplicate.

**Closed by jkwak-work** 2024-06-28 05:27 UTC
Labels: kind:question, priority:low, goal:client support
