### ISSUE TITLE
Compiler Crash when reading Primitive containing CullPrimitive in pixelshader

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#4108] opened 2024-05-04 20:49 UTC
With the following repro:
```hlsl
const static float2 positions[3] = {
    float2(0.0, -0.5),
    float2(0.5, 0.5),
    float2(-0.5, 0.5)
};

struct Vertex
{
    float4 pos : SV_Position;
};

struct Primitive
{
    bool cull : SV_CullPrimitive;
    [[vk::location(0)]] nointerpolation float3 test;
}

const static uint MAX_VERTS = 3;
const static uint MAX_PRIMS = 1;

void mesh_fn(    
    in uint tig,
    OutputIndices<uint3, MAX_PRIMS> triangles,
    OutputVertices<Vertex, MAX_VERTS> verts,
    OutputPrimitives<Primitive, MAX_PRIMS> primitives)
{
    const uint numVertices = 3;
    const uint numPrimitives = 1;
    SetMeshOutputCounts(numVertices, numPrimitives);

    if(tig < numVertices) {
        Vertex v;
        v.pos = float4(positions[tig], 0, 1);
        verts[tig] = v;
    }


    if(tig < numPrimitives) {
        triangles[tig] = uint3(0,1,2);
        primitives[tig].test = (float3(1,0,0));
        primitives[tig].cull = (false);
    }
}

[outputtopology("triangle")]
[numthreads(3, 1, 1)]
[shader("mesh")]
void entry_mesh(
    in uint tig : SV_GroupIndex,
    OutputIndices<uint3, MAX_PRIMS> triangles,
    OutputVertices<Vertex, MAX_VERTS> verts,
    OutputPrimitives<Primitive, MAX_PRIMS> primitives)
{
    mesh_fn(tig, triangles, verts, primitives);
}

struct FragmentOut
{
    [[vk::location(0)]] float3 color;
};

FragmentOut fragment(in Vertex vertex, in Primitive prim)
{
    FragmentOut frag_out;
    frag_out.color = prim.test;
    return frag_out;
}

[shader("fragment")]
FragmentOut entry_fragment(in Vertex vertex, in Primitive primitive)
{
    return fragment(vertex, primitive);
}
```

Causes slang to crash on a read access violation.

This sample specifically crashes slang but i also have a repro that does not crash slang but my nvidia vulkan driver shader compiler but i could not yet create a minimal repro for that.

I believe the SV_CullPrimitive causes some sort of problem here when passing the Primitive to a function.
When inlining the fragment shader function call and or removing the SV_CullPrimitive, this shader compiles. Otherwise slang reads invalid memory.

My config:
```
Slang Version: v2024.1.10
pc platform: x86-64msvc windows11
slang::TargetDesc::format: SlangCompileTarget::SLANG_SPIRV
slang::TargetDesc::profile: glsl_450+spirv_1_4
slang::TargetDesc::flags: SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY
slang::SessionDesc::defaultMatrixLayoutMode: SLANG_MATRIX_LAYOUT_COLUMN_MAJOR
```

**Comment by csyonghe** [comment] 2024-05-07 23:45
I must have missed any steps here, but I tried running `slangc your-file.slang -target spirv -o out.spv` and it succeeded without crashing.

**Comment by Ipotrick** [comment] 2024-05-10 20:46
I also use -O0 and -warnings-disable 39001, but other then that i dont do anything special i believe.

**Comment by bmillsNV** [comment] 2024-05-16 19:19
@Ipotrick we're unable to reproduce this. Can you retry on TOT and let us know the results?

**Comment by bmillsNV** [comment] 2024-05-30 19:12
Closing for now. Please re-open if you're able to reproduce with TOT.

**Closed by bmillsNV** 2024-05-30 19:12 UTC
Labels: kind:bug, goal:client support, Needs reporter feedback
