### ISSUE TITLE
ConstBufferPointer: Vulkan validation errors and aliasing issue

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3570] opened 2024-02-12 09:44 UTC
If a stride is declared in a ` ConstBufferPointer` , like this for example `ConstBufferPointer<Material,4> materialAddress;`  **WITHOUT** a space between the `, ` and the number.

Vulkan will throw the following error, but not if there is a **SPACE** in the declaration:

``` 
OpVariable 3727: expected AliasedPointer or RestrictPointer for PhysicalStorageBuffer pointer.
  %3727 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_PrimMeshInfoSlang Function
``` 

Commenting some lines in `Material` shows that the aliasing still isn't working, even with the proper syntax ` <Material, 4>` 
```
struct Material
{
  vec3  albedo;
  float roughness;
  float metallic;
  //float _pad0;
  //float _pad1;
  //float _pad2;
};
```

If the buffer of multiple material isn't padded, here is the result

| Expected | non-padded Material|
| --- | --- |
|![image](https://github.com/shader-slang/slang/assets/38076163/6766c222-fe31-4fce-88e0-a86367981228)|![image](https://github.com/shader-slang/slang/assets/38076163/31e4d45c-8839-40cd-a470-44832e79fd3a)|

Tested with Slang 2024.0.5
Vulkan SDK: 1.3.275
Sample: https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/ray_query

**Comment by mklefrancois** [comment] 2024-02-12 15:52
I have converted all `ConstBufferPointer<T>`  to `T*`

But I nevertheless have the following error
```
OpVariable 3581: expected AliasedPointer or RestrictPointer for PhysicalStorageBuffer pointer.
  %3581 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_PrimMeshInfoSlang Function
```

**Comment by csyonghe** [comment] 2024-02-12 20:15
Can you share the latest source that will reproduce the aliased decoration error and this image operand error?

**Comment by csyonghe** [comment] 2024-02-12 21:59
With PR #3574 and your tot example code (modified to use pointers instead of ConstBufferPointer), I can no longer reproduce any validation errors.

**Comment by csyonghe** [comment] 2024-02-12 22:24
Closing since I can no longer reproduce the validation errors with top of tree.

**Closed by csyonghe** 2024-02-12 22:24 UTC
Labels: priority:high

**Comment by csyonghe** [comment] 2024-02-12 22:29
Please give v2024.0.6 a try and feel free to open new issues if you are still seeing validation errors.

**Comment by mklefrancois** [comment] 2024-02-13 13:55
WIth v2024.0.6, I can no longer see any validation errors either. Thanks for the update
