### ISSUE TITLE
Leaking memory for witness table entries?

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#368] opened 2018-01-15 23:21 UTC
I think we are not properly freeing witness table entries as they are not owned by any class. The `IRValueList` does not seem to be responsible for freeing up the linked list it represents.

**Comment by tfoleyNV** [comment] 2018-01-16 02:33
This is basically a duplicate of #234, which notes that we leak all the IR structures at the moment.

**Closed** 2018-01-16 07:53 UTC
Labels: bug, ir
