### ISSUE TITLE
NSight graphics unable to correlate Slang with SPIRV/SASS

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#4975] opened 2024-08-30 20:42 UTC
I need to profile some high performance slang code, but it’s been difficult to understand the results I’m getting out of nsight compute.

The main issue I’m facing is that, even if I use “-g3” when I compile my slang code to SPIRV, nsight is unable to correlate the SPIR-V output with the slang source code. 

I can see debug instructions in the SPIRV, as well as the original source code at the top of the SPIRV. I can also see an embedded filename which is correct. So I’m not sure why correlation isn’t working.

I can also use the flag to avoid mangling variable names, and then the SPIRV becomes a bit more recognizable, but it’s still really tough to understand bottlenecks after a certain point.

Ultimately, I’m looking to get a similar result with Slang and Nsight Graphics as I do with CUDA and —line-info in Nsight compute. 

Is this expected to work today? Or are there still some features that needs adding for source -> disassembly correlation in nsight to work?

**Comment by natevm** [comment] 2024-08-31 08:24
Just to document current behavior a bit more clearly, 

In the screenshot below, I see that NSight is only able to determine a SASS to SPIRV correlation, but cannot correlate the SASS to Slang. 
![image](https://github.com/user-attachments/assets/2e535ad7-6a88-43b9-aa6e-95413adf2b23)

With DXC / HLSL, NSight Graphics produces direct HLSL to SASS correlation, which is indicated like this:
![image](https://github.com/user-attachments/assets/8ad0339b-c919-406f-a10d-01031c06dc7a)

As a consequence, it's very difficult to understand the output from NSight when using Slang over DXC.
Here's a screenshot of what "-g" currently produces:
![image](https://github.com/user-attachments/assets/335a0d4f-e2cb-495f-bf5e-308cb06dab89)

When I click the dropdown where I'd expect HLSL or Slang, all I see is SPIRV and disassembly, which is difficult to decipher. 
![image](https://github.com/user-attachments/assets/918a66fe-1b7e-4879-8608-21828b67d0d5)

**Comment by csyonghe** [comment] 2024-09-17 00:34
We have reproduced this issue and created a repro package for the nsight team to investigate. Since this is not a Slang issue, we will close this for now. We will report back here if we hear any updates.

**Closed by csyonghe** 2024-09-17 00:34 UTC
Labels: kind:question, goal:client support

**Comment by csyonghe** [comment] 2024-09-23 20:11
This has been fixed in top of tree nsight, and may be made available in the next nsight release.
![image](https://github.com/user-attachments/assets/0da63296-75ae-4f87-88ae-bd29f8aace13)
