### ISSUE TITLE
Shader constants not working?

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#3581] opened 2024-02-14 10:05 UTC
I want to use a shader with a shader constant like this

```glsl
layout(constant_id = 0) const int MULTIPLIER = 0;
```

but the code generated by slang always wants to use a uniform descriptor at Set 0 Binding 1. Is this not implemented or is this a bug? I am using vulkan.

edit: Not talking about the slang feature #3565 but the functionality used in vulkan, slang just needs to generate spirv that allows this

**Comment by csyonghe** [comment] 2024-02-14 17:03
Specialization constants are not supported in Slang mostly because we aren't seeing a clear benefit of it and none of our existing users have requested it.

**Comment by fknfilewalker** [comment] 2024-02-16 09:31
Is this something you would merge? If so, could you point me to the important locations in the code, then I could take a look at it.

**Comment by csyonghe** [comment] 2024-02-16 15:19
Yes, we welcome contributions.

You can take a look at how push constants are handled and add another case for specialization constants. It will be nontrivial amount of work considering it affects parameter layout and reflection.

**Comment by swoods-nv** [comment] 2024-02-16 15:35
Marking this as Q3 milestone because we don't plan to take near term action, but it needs a milestone to be considered triaged.

**Comment by swoods-nv** [comment] 2024-06-12 18:25
Removing milestone, because it's not being worked within the team (and is still considered triaged because it has a label)

**Comment by mmgeorge** [comment] 2024-08-01 21:56
I could also see this being pretty useful should slang also target wgsl / web platforms. The issue is that we need the ability to specialize shaders when creating render pipelines. I suppose if we wanted to use slang, the only alternative would be to try and compile the compiler / linker to wasm.

**Closed** 2024-08-30 19:03 UTC
Labels: goal:quality & productivity
