### ISSUE TITLE
Loop unrolling and compile-time constant parameters

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#403] opened 2018-02-08 18:59 UTC
We eventually need to implement the semantics of the HLSL `[unroll]` attribute in our back-end. Furthermore, to really match the behavior people expect when generating GLSL/SPIR-V we may also need to detect loops that require unrolling (even if the user hasn't added the `[unroll]` atribute).

An important challenge is that a loop that needs unrolling might be in a function, where the loop termination depends on a function parameter. In that case, we also have an implicit restriction that the function parameter needs to be a compile-time-constant. (Also, when generating GLSL/SPIR-V we'd need to ensure that we either inline the function or specialize it for each call site).

My proposed model for implementing this is to add a notion something like C++ `constexpr` (I'd prefer either `constant` or `@Constant`...), and then allow functions to have `constant` parameters. When calling a function with a `constant` parameter, the corresponding argument would then be restricted to be `constant`, etc.

(Note: if should in principle be possible for interface requirements to have `constant` parameters, which would then *allow* (but not require) an implementation to mark the corresponding parameter as `constant`)

In addition to an explicit `constant` modifier, we'd probably also need an `implicitlyConstant` modifier that indicates that a parameter needs to be a compile-time constant, but the front-end can't actually enforce this because of HLSL compatiblity.

After generating initial IR in the front-end, we can identify SSA instructions that need to be `constant` (either explicitly or implicitly) and then do a backwards dataflow pass to infer instructions that need to be constant in order to make things work (e.g., if `c = a + b` and `c` is implicitly `constant`, then we can infer that `a` and `b` are implicitly `constant`, etc.).

(If a function call instruction gets marked `constant`, then we need to ensure that it is a function we can constant-fold; for now that might be limited to a pre-selected set of builtins, but eventually it should be possible for the user to mark functions with the equivalent of C++ `constexpr`)

When an ordinary block parameter needs to be `constant`, we first need to make sure that any argument passed to the block for that parameter is also `constant`. In principle we also need to ensure that any branch decision that determines which entry edge for the block gets taken is based on a `constant` value. Getting that bit right will require computing a control dependence graph, and then figuring out how to use it to isolate the conditions we care about.

A loop that is marked `[unroll]` should force any branch condition that the loop header is control-dependent on to be marked `constant` (if I'm understanding correctly).

If a function parameter that wasn't explicitly marked `constant` gets inferred to be `constant`, then we'd need to issue an error message if that function is part of the public interface of a module being compiled as a library, *or* is used to satisfy an interface requirement (that is, it is referenced in a witness table entry). For backwards compatibility, a user module being compiled for its entry points would be considered to have no public symbols.

Once a function parameter is inferred to be `constant`, any call sites for the function need to infer the corresponding argument to be `constant`. (For calls into interface methods with `constant` parameters, the front-end should have done the marking).

All of the marking can in principle be done during front-end IR generation, because there will be explicit `constant` annotations on any imported symbols so that the inference step doesn't need to cross module boundaries.

In the back-end, once the full call graph is fixed (all specialization has been performed), We should be able to perform a kind of specialization step where a specialization is triggered for a function + a list of values for its `constant` parameters. Functions with no `constant` parameters would form the initial work list.

Within a function, the specialization process can work by lazily constructing specialized blocks (or re-using existing unspecialized blocks). Similar to the case for functions, the per-block specialization step would use a cache indexed on a block + values for the `constant` parameter of the block (and intially the work-list starts with the entry block).

When specializing a block we can directly re-use (or clone...) the non-`constant` instructions in the body, and constant-fold the `constant` instructions. When we reach the end of the block, we can identify specialized successor blocks that need to be generated. (We should avoid requesting/generating successors in cases where the branch condition is a known constant...)

(One gotcha I'm just realizing there is that the right specialization for a block might also depend on how any of its dominators have been specialized, so the keying needs bit more thought than block+arguments)

If we do this right, it should serve to both perform simple specialization for constant values *and* loop unrolling. One big gotcha is that nothing about the `constant` propagation step will ensure that a loop that needs to be unrolled will actual unroll to a finite number of blocks, so we'd probably need to have a termination condition like `fxc` for the case where a loop takes too long to unroll.

**Comment by tfoleyNV** [comment] 2018-02-22 17:10
The more I think about this, the more I'm convinced I don't know what the definitions should be for the two big challenges here:

### Loop Unrolling

When we decide that a loop should be `[unroll]`ed, which values in the IR should then be marked as constants? My original message says anything that a loop back-edge is control-dependent on, which seems reasonable, but rules out certain cases where you have a loop with a bounded number of iterations, but also some early-exit conditions.

As an example:

```hlsl
for(int ii = 0; ii < COUNT; ++ii) {
    if(someBuffer[ii]) break;
    // do stuff
}
```

The challenge in that example is that the loop body first tests the `ii < COUNT` condition, which is the one we expect to turn out to be `constexpr`, and then tests `someBuffer[ii]`, which is never going to be `constexpr`.

If we compute control-dependence for this code, we'll find that hte loop back-edge is control-dependent on the second test, and not the first (because the second test is that one that leads to the back-edge definitely being executed).

For the loop to be unroll-able, we really just require that *one* of the loop termination conditions is a constant expression. That is, for any path from the loop header back to itself, there should be at least one block with a branch based on a constant condition where the alternative not taken can lead out of the loop.

The challenge in a case like this is then in identifying *which* conditions inside the loop should be the ones marked as constants. 

### Propagation of Constant-ness

The other problem continues to be propagation of constant-ness in the presence of control flow.

Specifically, when we discover that a "phi" needs to provide a constant result (and lets assume for now that it is not a phi in a loop header...), we need to identify which branch conditions should be marked constant, such that it will always be statically determined which edge is used to enter the block.

(Actually, we'd really want to identify which *equivalence class* of incoming edges is taken, using equivalence of constant arguments provided to the block. One could imagine a pre-process that identifies when multiple predecessors of a block with a phi pass in the same arguments (for constant parametesr) and replace them with a new block that represents the merge of all of them, after which each equivalence class would show up as a single edge...)

A naive answer would be to look at the predecessors of the phi block, and find conditions that each of them is control-dependent on. The problem is that control dependence tells us "when this condition goes a certain way, this block/edge is *definitely* executed," and we actually don't care about when the block is definitely executed - we care that in cases where the phi is going to be executed a particular predecessor will be executed.

To try to make a concrete example:

```hlsl
for(...) {
    int x = 0;
    if(someCondition) {
        if(someOtherCondition) continue;
        x = 1;
    }
    callThatRequiresConstant(x);
}
```

In this example, the edge that would pass `x = 1` to `callThatRequiresConstant` is control-dependent on `someOtherCondition` and not `someCondition`, but looking at the code above, it is clear that for constant-ness to be correct here, we require that `someCondition` be marked constant, and we don't actually care about `someOtherCondition` (whether or not it is true doesn't affect what value the downstream call sees).

**Comment by tfoleyNV** [comment] 2018-02-22 18:06
Okay, I think I've got an idea of how to solve the second problem ("I need this block parameter to be constant, what conditions also need to be constant?") using an iterated solver on the CFG.

For every block, we'd define its corresponding "decision-maker" block, which is conceptually the block that decides what value(s) reach the constant parameter(s) of our target block `X`.

The decision-maker block for each predecessor `P` of `X` will be initialized with `P` itself, because `P` determines which values reach `X`. If we want to get fancy, we could pick one representative predecessor for each unique equivalence class of values being passed along.

The decision-maker for all other blocks would be initialized to `null` to indicate that we don't even know if `X` is reachable from those blocks.

Now we can iterate to update the decision-maker for each block `B`, based on its successors:

* If there is only one successor `S` and `decisionMaker(S)` is non-null, then set `decisionMaker(B)` to `decisionMaker(S)`.

* If there are multiple successors, but there is only one non-null decision-maker between them, then set `decisionMaker(B)` to that decision-maker block

* If the successors have more than one unique non-null decision maker, then set `decisionMaker(B)` to `B` itself

This should be monotonic, so that the decision-maker for a block can only ever change from null, to the block itself, to some other block.

We might need to be a little careful to not overwrite the decision-maker for any of the predecessors of `X`, and we shouldn't need a decision-maker for `X` at all. In fact, we should not bother going past the immediate dominator of `X` in the CFG, since control-flow decisions there can affect the flow of *values* to `X`, but not the edge used to enter `X`.

(I'll need to go to a whiteboard and convince myself this will actually work in the presence of loops)

After things have converged, any block that has multiple non-null decision-makers among its successors would need to constrain its branch condition to be a constant. This *might* work.

**Comment by csyonghe** [comment] 2023-04-04 22:13
This is implemented. We now have `[ForceUnroll]` and basic AST-level analysis of static loop bounds.

**Closed by csyonghe** 2023-04-04 22:13 UTC
Labels: kind:enhancement, area:ir, priority:medium
