### ISSUE TITLE
Shaders using Texture.Load do not produce valid GLSL shader

### ISSUE THREAD

**Issue by kyaoNV** [shader-slang/slang#683] opened 2018-10-18 01:04 UTC
I'm encountering this error on Vulkan instance/runtime version 1.1.82:
`'texelFetch' : required extension not requested: GL_EXT_samplerless_texture_functions`
Tested on Slang 0.10.35, and 0.11.x

Does not appear to occur on VK version 1.1.77.

**Comment by tfoleyNV** [comment] 2018-10-18 16:34
I'm a bit confused, since this seems to be an error message coming from glslang, and because Slang bundles its own version of glslang into its build I'm not clear on how changing the version of the Vulkan runtime could affect things.

**Comment by tfoleyNV** [comment] 2018-10-19 20:20
PRs #685 and #686 should resolve the regression that was introduced.

**Comment by tfoleyNV** [comment] 2018-10-19 21:21
Should be fixed in `v0.10.36` and `v0.11.3` when it goes live.

**Closed by tfoleyNV** 2018-10-19 21:21 UTC
Labels: bug, cross compilation, ir, standard library
